Builder classes for action classes
delta-io/connectors pull request #123
Opened 2021-08-30 18:42 UTC by allisonport-db

Many of the Java Action classes have large constructors, and Java doesn't allow default values. This pr adds builder classes for `AddFile`, `RemoveFile`, `CommitInfo`, `Metadata`, `JobInfo`.

2021-09-02 04:14 UTC, zsxwing commented on hive/src/main/scala/io/delta/hive/DeltaHelper.scala
> +        val f = new AddFile.AddFileBuilder(
For the builder pattern, we usually add a static builder method and just call the class `Builder`. E.g,

```
AddFile.builder(...).build()
```

We can use Guava as an example: 
- https://github.com/google/guava/blob/v30.1.1/guava/src/com/google/common/collect/ImmutableMap.java#L179
- https://github.com/google/guava/blob/v30.1.1/guava/src/com/google/common/collect/ImmutableMap.java#L367

2021-09-02 04:14 UTC, zsxwing commented on standalone/src/main/java/io/delta/standalone/actions/AddFile.java
> +            AddFile addFile = new AddFile(this);
It's better to call the existing constructor directly rather than adding a new private AddFile constructor.

2021-09-02 15:40 UTC, scottsand-db commented on hive/src/main/scala/io/delta/hive/DeltaHelper.scala
> +        val f = new AddFile.AddFileBuilder(
This is my bad. In the Jira description, I referenced a java builder example that used this static class.
Luckily, this is easy to refactor!

2021-09-02 15:43 UTC, scottsand-db commented on standalone/src/main/java/io/delta/standalone/actions/CommitInfo.java
> +     * Builder class for CommitInfo. Enables construction of RemoveFile object with default values.
nit: CommitInfo instead of RemoveFile

2021-09-02 15:44 UTC, scottsand-db commented on standalone/src/main/java/io/delta/standalone/actions/AddFile.java
> +        // add default values here, or in the constructor (values besides null)
nit: remove comment

2021-09-02 15:44 UTC, scottsand-db commented on standalone/src/main/java/io/delta/standalone/actions/AddFile.java
> +        // add default values here, or in the constructor (values besides null)
it would also be nice to comment
```
// required AddFile params
private final String path;
...

// optional AddFile params
private String stats;
```

2021-09-02 15:45 UTC, scottsand-db commented on standalone/src/main/java/io/delta/standalone/actions/AddFile.java
> +            AddFile addFile = new AddFile(this);
+1. Again, my fault for referencing a java buidler pattern example in the Jira ticket that did it this way. Again, seems easy to refactor :)

2021-09-02 15:58 UTC, scottsand-db commented on standalone/src/main/java/io/delta/standalone/actions/CommitInfo.java
> +
since we are switching to `CommitInfo.build().version(..).timestamp(..)` this will need a default, empty constructor

2021-09-02 15:59 UTC, scottsand-db commented on standalone/src/main/java/io/delta/standalone/actions/CommitInfo.java
> +
this is only because all the member fields here are optional

2021-09-02 16:01 UTC, scottsand-db commented on standalone/src/main/java/io/delta/standalone/actions/JobInfo.java
> +     * Builder class for JobInfo. Enables construction of RemoveFile object with default values.
nit: JobInfo instead of RemoveFile

2021-09-02 16:04 UTC, scottsand-db requested changes
Great PR and thanks for doing this! Let a few minor comments.

Also, this may be overkill, but we should also include a simple test suite to, at the very least, exemplify how we expect users to use these builders.

@zsxwing what do you think?

2021-09-03 21:58 UTC, scottsand-db approved these changes
LGTM

2021-09-03 21:58 UTC, scottsand-db commented on standalone/src/main/java/io/delta/standalone/actions/CommitInfo.java
> +
nit: remove line

2021-09-08 18:40 UTC, zsxwing reviewed
The code changes look good to me. Could you add tests for these builder classes? Just one test for each type, such as

```
addFileFromBuilder = AddFile.builder().....build()
addFileFromConstructor = new AddFile(...)
assert(addFileFromBuilder == addFileFromConstructor)
```

This will ensure we pass the parameters correctly in builder classes.

2021-09-09 22:01 UTC, allisonport-db commented on standalone/src/main/java/io/delta/standalone/actions/RemoveFile.java
> +    }
Is there a reason `RemoveFile` didn't override `equals()` and `hashCode()` before? Needed to override `equals()` for testing purposes.

2021-09-10 15:36 UTC, scottsand-db commented on standalone/src/main/java/io/delta/standalone/actions/RemoveFile.java
> +    }
it should have been there, so thanks for adding it!

2021-09-10 17:16 UTC, allisonport-db commented on standalone/src/test/scala/io/delta/standalone/internal/DeltaLogSuite.scala
> +      .schema(new StructTypeJ(Array(new StructFieldJ("test_field", new IntegerType())))).build()
Is there any style rule for this sort of chained method invocation?

2021-09-10 18:21 UTC, scottsand-db commented on standalone/src/test/scala/io/delta/standalone/internal/DeltaLogSuite.scala
> +      .schema(new StructTypeJ(Array(new StructFieldJ("test_field", new IntegerType())))).build()
I don't see it specifically mentioned on the DB style guide. https://github.com/databricks/scala-style-guide#chaining.

However, I think one on each line looks most readable here?
```
MetadataJ.builder()
  .id("test_id")
  .name("test_name")
  .description("test_description")
  .format(new FormatJ("csv", Collections.emptyMap()))
  ...
```

2021-09-10 18:54 UTC, zsxwing commented on standalone/src/test/scala/io/delta/standalone/internal/DeltaLogSuite.scala
> +      .schema(new StructTypeJ(Array(new StructFieldJ("test_field", new IntegerType())))).build()
+1 for one on each line

2021-09-10 18:55 UTC, zsxwing approved these changes
Thanks! LGTM.

2021-09-13 20:09 UTC, merged