support partition columns value fetch on row iterator
delta-io/connectors pull request #127
Opened 2021-09-07 02:19 UTC by wwang-talend

2021-09-07 22:11 UTC, scottsand-db requested changes
Great work and thanks for doing this!

Main things to fix are:
- styling concerns. Make sure you follow the https://github.com/databricks/scala-style-guide
- more thorough tests.

Cheers

2021-09-07 22:11 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/data/RowParquetRecordImpl.scala
>    override def getLength: Int = record.length
`record.length + partitionValues.size`

2021-09-07 22:11 UTC, scottsand-db commented on standalone/src/test/scala/io/delta/standalone/internal/DeltaDataReaderSuite.scala
> +    withLogForGoldenTable("From_Deltalake_Partition") { log =>
`"data-reader-partition-values"` is a better name for this table

2021-09-07 22:11 UTC, scottsand-db commented on standalone/src/test/scala/io/delta/standalone/internal/DeltaDataReaderSuite.scala
> +  test("get partition") {
`"data reader can read partition values"` is a better name for this test

2021-09-07 22:11 UTC, scottsand-db commented on standalone/src/test/scala/io/delta/standalone/internal/DeltaDataReaderSuite.scala
> +    withLogForGoldenTable("From_Deltalake_Partition") { log =>
you should also add a generateGoldenTable 'test case' to actually generate this table in GoldenTables.scala

2021-09-07 22:11 UTC, scottsand-db commented on standalone/src/test/scala/io/delta/standalone/internal/DeltaDataReaderSuite.scala
> +    withLogForGoldenTable("From_Deltalake_Partition") { log =>
I would also like to see
a) more data types used as partition values
b) don't just assert that the partition value is not null, but actually the correct anticipated value. why not just create some data with both the expected partition value, and a row column (integer), and use that row number to help you determine what the expected partition value is
c) more than one partition

2021-09-07 22:11 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/data/CloseableParquetDataIterator.scala
> +
this would be a good place for https://github.com/delta-io/delta/blob/master/PROTOCOL.md#Partition-Value-Serialization

2021-09-07 23:04 UTC, scottsand-db commented on standalone/src/test/scala/io/delta/standalone/internal/DeltaDataReaderSuite.scala
> +    withLogForGoldenTable("From_Deltalake_Partition") { log =>
also some tests for null edge cases

2021-09-13 03:20 UTC, wwang-talend commented
hi @scottsand-db , thanks for the review, have fixed them all except test parts, will fix it too soon

2021-09-13 15:30 UTC, scottsand-db requested changes
just requested some super small changes, but overall LGTM.

2021-09-13 15:30 UTC, scottsand-db commented on golden-tables/src/test/scala/io/delta/golden/GoldenTables.scala
> +  TODO fix it
can you please create an issue detailing what is wrong here and how to reproduce the issue?

2021-09-13 15:30 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/data/RowParquetRecordImpl.scala
> +    if (partitionValues.contains(fieldName)) {// partition field
nit: `{ //`

2021-09-13 15:30 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/data/RowParquetRecordImpl.scala
> +                case y: RowParquetRecord => RowParquetRecordImpl(y, x, timeZone, partitionValues)
some weird indentation here.

2021-09-14 02:05 UTC, wwang-talend commented on standalone/src/main/scala/io/delta/standalone/internal/data/RowParquetRecordImpl.scala
> +                case y: RowParquetRecord => RowParquetRecordImpl(y, x, timeZone, partitionValues)
if not that, will throw a compiler issue as too long code line

2021-09-14 02:14 UTC, wwang-talend commented on golden-tables/src/test/scala/io/delta/golden/GoldenTables.scala
> +  TODO fix it
i run this in scala notebook in azure databricks:

```
import java.sql.Timestamp
import java.sql.Date
import java.math.{BigDecimal => JBigDecimal}
import org.apache.spark.sql.types._

spark.conf.set("fs.azure.account.auth.type.xxx.dfs.core.windows.net", "SharedKey")
spark.conf.set("fs.azure.account.key.xxx.dfs.core.windows.net", "xxx")

def createRow(i: Int): Row = {
      Row(Array[Byte](i.toByte, i.toByte), i.toString)
    }

    def createRowWithNullValues(): Row = {
      Row(null, "2")
    }

    val schema = new StructType()
      .add("as_binary", BinaryType)
      .add("value", StringType)

    val data = createRowWithNullValues() +: (0 until 2).map(createRow)

val df = spark.createDataFrame(spark.sparkContext.parallelize(data), schema)
df.write.format("delta").mode("overwrite").option("overwriteSchema", "true")
.partitionBy("as_binary")
.save("abfss://xxx@xxx.dfs.core.windows.net/xxx")
```

the exception info:
```
Job aborted.
Caused by: Job aborted due to stage failure.
Caused by: Task failed while writing rows.
Caused by: AbfsRestOperationException: Operation failed: "Bad Request", 400, PUT, https://compqastoragegen2.dfs.core.windows.net/csv/azuregen2tuj/data-reader-partition-values2/as_binary%3D%00%00/part-00005-85764fe9-3e2a-417d-845f-0c751364e67a.c000.snappy.parquet?resource=file&timeout=90, , ""
```

```
at org.apache.spark.sql.execution.datasources.FileFormatWriter$.write(FileFormatWriter.scala:289)
	at com.databricks.sql.transaction.tahoe.files.TransactionalWriteEdge.$anonfun$writeFiles$5(TransactionalWriteEdge.scala:265)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withCustomExecutionEnv$5(SQLExecution.scala:126)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:267)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withCustomExecutionEnv$1(SQLExecution.scala:104)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:852)
	at org.apache.spark.sql.execution.SQLExecution$.withCustomExecutionEnv(SQLExecution.scala:77)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:217)
	at com.databricks.sql.transaction.tahoe.files.TransactionalWriteEdge.$anonfun$writeFiles$1(TransactionalWriteEdge.scala:221)
	at com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:80)
	at com.databricks.sql.transaction.tahoe.metering.DeltaLogging.$anonfun$recordDeltaOperation$5(DeltaLogging.scala:115)
	at com.databricks.logging.UsageLogging.$anonfun$recordOperation$4(UsageLogging.scala:434)
	at com.databricks.logging.UsageLogging.$anonfun$withAttributionContext$1(UsageLogging.scala:240)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at com.databricks.logging.UsageLogging.withAttributionContext(UsageLogging.scala:235)
	at com.databricks.logging.UsageLogging.withAttributionContext$(UsageLogging.scala:232)
	at com.databricks.spark.util.PublicDBLogging.withAttributionContext(DatabricksSparkUsageLogger.scala:19)
	at com.databricks.logging.UsageLogging.withAttributionTags(UsageLogging.scala:279)
	at com.databricks.logging.UsageLogging.withAttributionTags$(UsageLogging.scala:271)
	at com.databricks.spark.util.PublicDBLogging.withAttributionTags(DatabricksSparkUsageLogger.scala:19)
	at com.databricks.logging.UsageLogging.recordOperation(UsageLogging.scala:415)
	at com.databricks.logging.UsageLogging.recordOperation$(UsageLogging.scala:341)
	at com.databricks.spark.util.PublicDBLogging.recordOperation(DatabricksSparkUsageLogger.scala:19)
	at com.databricks.spark.util.PublicDBLogging.recordOperation0(DatabricksSparkUsageLogger.scala:56)
	at com.databricks.spark.util.DatabricksSparkUsageLogger.recordOperation(DatabricksSparkUsageLogger.scala:129)
	at com.databricks.spark.util.UsageLogger.recordOperation(UsageLogger.scala:70)
	at com.databricks.spark.util.UsageLogger.recordOperation$(UsageLogger.scala:57)
	at com.databricks.spark.util.DatabricksSparkUsageLogger.recordOperation(DatabricksSparkUsageLogger.scala:85)
	at com.databricks.spark.util.UsageLogging.recordOperation(UsageLogger.scala:402)
	at com.databricks.spark.util.UsageLogging.recordOperation$(UsageLogger.scala:381)
	at com.databricks.sql.transaction.tahoe.OptimisticTransaction.recordOperation(OptimisticTransaction.scala:91)
	at com.databricks.sql.transaction.tahoe.metering.DeltaLogging.recordDeltaOperation(DeltaLogging.scala:113)
	at com.databricks.sql.transaction.tahoe.metering.DeltaLogging.recordDeltaOperation$(DeltaLogging.scala:97)
	at com.databricks.sql.transaction.tahoe.OptimisticTransaction.recordDeltaOperation(OptimisticTransaction.scala:91)
	at com.databricks.sql.transaction.tahoe.files.TransactionalWriteEdge.writeFiles(TransactionalWriteEdge.scala:161)
	at com.databricks.sql.transaction.tahoe.files.TransactionalWriteEdge.writeFiles$(TransactionalWriteEdge.scala:157)
	at com.databricks.sql.transaction.tahoe.OptimisticTransaction.writeFiles(OptimisticTransaction.scala:91)
	at com.databricks.sql.transaction.tahoe.files.TransactionalWriteEdge.writeFiles(TransactionalWriteEdge.scala:301)
	at com.databricks.sql.transaction.tahoe.files.TransactionalWriteEdge.writeFiles$(TransactionalWriteEdge.scala:298)
	at com.databricks.sql.transaction.tahoe.OptimisticTransaction.writeFiles(OptimisticTransaction.scala:91)
	at com.databricks.sql.transaction.tahoe.commands.WriteIntoDelta.write(WriteIntoDelta.scala:113)
	at com.databricks.sql.transaction.tahoe.commands.WriteIntoDelta.$anonfun$run$2(WriteIntoDelta.scala:72)
	at com.databricks.sql.transaction.tahoe.commands.WriteIntoDelta.$anonfun$run$2$adapted(WriteIntoDelta.scala:71)
	at com.databricks.sql.transaction.tahoe.DeltaLog.withNewTransaction(DeltaLog.scala:207)
	at com.databricks.sql.transaction.tahoe.commands.WriteIntoDelta.$anonfun$run$1(WriteIntoDelta.scala:71)
	at com.databricks.sql.acl.CheckPermissions$.trusted(CheckPermissions.scala:1258)
	at com.databricks.sql.transaction.tahoe.commands.WriteIntoDelta.run(WriteIntoDelta.scala:70)
	at com.databricks.sql.transaction.tahoe.sources.DeltaDataSource.createRelation(DeltaDataSource.scala:164)
	at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:48)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:75)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:73)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:96)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$execute$1(SparkPlan.scala:196)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:240)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:165)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:236)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:192)
	at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:167)
	at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:166)
	at org.apache.spark.sql.DataFrameWriter.$anonfun$runCommand$1(DataFrameWriter.scala:1079)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withCustomExecutionEnv$5(SQLExecution.scala:126)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:267)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withCustomExecutionEnv$1(SQLExecution.scala:104)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:852)
	at org.apache.spark.sql.execution.SQLExecution$.withCustomExecutionEnv(SQLExecution.scala:77)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:217)
	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:1079)
	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:468)
	at org.apache.spark.s [...]

2021-09-14 15:42 UTC, scottsand-db requested changes
One last styling change requested. Also, please resolve comments for changes you have already addressed (as that will make the review easier for a second reviewer).

2021-09-14 15:42 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/data/RowParquetRecordImpl.scala
> +                case y: RowParquetRecord => RowParquetRecordImpl(y, x, timeZone, partitionValues)
it should be 
```
listVal.map {
  case y: RowParquetRecord => RowParquetRecordImpl(y, x, timeZone, partitionValues)
}.asJava
```

2021-09-24 09:20 UTC, wwang-talend commented
hi @scottsand-db , have fixed them all, please help review, thanks.

2021-09-27 21:40 UTC, scottsand-db approved these changes
LGTM.

2021-09-28 22:01 UTC, zsxwing requested changes
Thanks for the PR. Left some comments

2021-11-05 22:06 UTC, zsxwing commented
This is merged as a part of #197

2021-11-05 22:06 UTC, closed without merging