add metadata to StructField
delta-io/connectors pull request #130
Opened 2021-09-07 18:40 UTC by allisonport-db

Currently the DSR ignores column metadata when reading the schema. This PR adds column metadata to `DataTypeParser` and provides access to the user through `StructField`.
Changes:
• Add metadata field to `StructField`
• Include column metadata in `toJson` and `fromJson`
• Tests for schemas with column metadata

2021-09-07 18:42 UTC, allisonport-db commented on standalone/src/main/scala/io/delta/standalone/internal/util/DataTypeParser.scala
> +         metadata.obj.toMap[String, AnyRef].asJava)
This stores the metadata values inn StructField as a JValue, is that what we want?

2021-09-07 20:56 UTC, scottsand-db requested changes
By biggest question, and this will help answer your question of "should we store the metadata map values in StructField as a JValue", is why aren't we including a `FieldMetadataBuilder.java` and `FieldMetadata.java` like [spark/.../Metadata](https://github.com/apache/spark/blob/master/sql/catalyst/src/main/scala/org/apache/spark/sql/types/Metadata.scala) does?(renamed to put the `Field` keyword in there to avoid confusion with `actions/Metadata.java`)

Since we are exposing a `Map<String, Object>`, users can put an entry `("foo", new Foo())`. This would break things during serialization, and we want to prevent that. Limiting the column metadata value types would help prevent this.

I think this should look more like [spark/.../Metadata](https://github.com/apache/spark/blob/master/sql/catalyst/src/main/scala/org/apache/spark/sql/types/Metadata.scala).

@zsxwing what do you think?

2021-09-07 20:56 UTC, scottsand-db commented on standalone/src/main/java/io/delta/standalone/types/StructField.java
> +     * @param metadata metadata for this field
nit: add another space

2021-09-07 20:56 UTC, scottsand-db commented on standalone/src/test/scala/io/delta/standalone/internal/DeltaDataReaderSuite.scala
> +        |{"name":"a","type":"integer","nullable":true,"metadata":{"test":"foo"}},
you should also test an empty metadata here

2021-09-07 21:00 UTC, scottsand-db commented on standalone/src/test/scala/io/delta/standalone/internal/DeltaDataReaderSuite.scala
> +    val schema_str =
super small nit: schemaStr instead

2021-09-09 17:59 UTC, zsxwing commented on standalone/src/main/scala/io/delta/standalone/internal/util/DataTypeParser.scala
> +         metadata.obj.toMap[String, AnyRef].asJava)
We should not expose JValue in public APIs. Could you convert them to java objects instead?

2021-09-09 18:00 UTC, zsxwing commented
> Since we are exposing a `Map<String, Object>`, users can put an entry `("foo", new Foo())`. This would break things during serialization, and we want to prevent that. Limiting the column metadata value types would help prevent this.

Yep. This is a good idea.

2021-09-13 18:55 UTC, allisonport-db commented on standalone/src/main/java/io/delta/standalone/types/FieldMetadata.java
> +    // TODO: should this be an immutable map created via the builder?
should this be an immutable map?

2021-09-13 18:56 UTC, allisonport-db commented on standalone/src/main/scala/io/delta/standalone/internal/util/DataTypeParser.scala
> +  def metadataValueToJValue(value: Any): JValue = {
Why are some functions in DataTypeParser private and others aren't? Should this one be private?

2021-09-13 18:57 UTC, allisonport-db commented
@zsxwing ready for another look

2021-09-13 21:26 UTC, scottsand-db approved these changes
LGTM with a few minor comments

2021-09-13 21:26 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/util/DataTypeParser.scala
> +  def metadataValueToJValue(value: Any): JValue = {
Good catch. The only public ones should be `toJson` and `fromJson`; everything else can be private.

2021-09-13 21:26 UTC, scottsand-db commented on standalone/src/main/java/io/delta/standalone/types/FieldMetadata.java
> +        public Builder putLong(String key, Long value) {
@zsxwing what do you think?

2021-09-15 00:27 UTC, allisonport-db commented on standalone/src/main/java/io/delta/standalone/types/FieldMetadata.java
> +        public Builder putLong(String key, Long value) {
Makes sense since there's also already `putNull()`. 

@zsxwing @scottsand-db 
What about for the arrays? Is there a situation where an array metadata value might have null as an element?

2021-09-15 15:41 UTC, scottsand-db commented on standalone/src/main/java/io/delta/standalone/types/FieldMetadata.java
> +        public Builder putLong(String key, Long value) {
I would go with whatever Ryan says here. For me, using primitives seems fine.

2021-09-16 06:58 UTC, zsxwing reviewed
Left some minor comments. Great work!

2021-09-16 06:58 UTC, zsxwing commented on standalone/src/main/java/io/delta/standalone/types/FieldMetadata.java
> +        return metadata.entrySet()
It's better to add a toJson method and make `toString` return it. Otherwise, this `toString` implementation doesn't work for Array type.

2021-09-16 06:58 UTC, zsxwing commented on standalone/src/main/java/io/delta/standalone/types/FieldMetadata.java
> +    public int hashCode() { return metadata.hashCode(); }
Similar to `equals`, we need to handle Array type here as well. Otherwise, it's possible that equals return true but the two objects have different hash codes.

2021-09-20 16:45 UTC, allisonport-db commented on standalone/src/main/java/io/delta/standalone/types/FieldMetadata.java
> +        return metadata.entrySet()
I updated this so it should work with Array type. The `toJson` method is in `DataTypeParser` is it preferable to reference that from here instead? This function is for `StructField.buildFormattedString`

2021-09-20 23:55 UTC, zsxwing approved these changes
LGTM

2021-09-20 23:55 UTC, zsxwing commented on standalone/src/main/java/io/delta/standalone/types/FieldMetadata.java
> +            return metadata.entrySet()
nit: indent

2021-09-21 15:27 UTC, scottsand-db commented on standalone/src/main/java/io/delta/standalone/types/FieldMetadata.java
> +            return metadata.entrySet()
I'll add investigating Java formatting tests as a ticket, should help both of us with our java code.

2021-09-21 18:44 UTC, merged