Expression framework skeleton
delta-io/connectors pull request #155
Opened 2021-09-24 22:50 UTC by scottsand-db

2021-09-24 22:57 UTC, scottsand-db commented
I'll fix failing scalstyle Monday

2021-09-27 18:54 UTC, zsxwing requested changes

2021-09-27 18:54 UTC, zsxwing commented on standalone/src/main/java/io/delta/standalone/expressions/Util.java
> +package io.delta.standalone.expressions;
This should be in private package.

2021-09-27 18:54 UTC, zsxwing commented on standalone/src/main/java/io/delta/standalone/expressions/CastingComparator.java
> +public class CastingComparator<T extends Comparable<T>> {
Any reason we cannot use `Comparable<T>` directly?

2021-09-27 18:54 UTC, zsxwing commented on standalone/src/main/scala/io/delta/standalone/internal/DeltaLogImpl.scala
> +  def filterFileList(
This is not needed for #136. Could you remove it?

2021-09-27 18:54 UTC, zsxwing commented on standalone/src/main/scala/io/delta/standalone/internal/data/PartitionRowRecord.scala
> +private[internal] class PartitionRowRecord(
Remove this since it's not ready. We can use the existing `RowParquetRecordImpl` to write unit tests for expressions.

2021-09-27 18:54 UTC, zsxwing commented on standalone/src/main/java/io/delta/standalone/expressions/And.java
> +            throw new RuntimeException("'And' expression children.eval results must be Booleans");
We can use `IllegalArgumentException` for all of checks done in expressions.

2021-09-27 18:54 UTC, zsxwing commented on standalone/src/main/java/io/delta/standalone/expressions/BinaryExpression.java
> +    protected abstract Object nullSafeEval(Object leftResult, Object rightResult);
nit: missing javadoc

2021-09-27 18:54 UTC, zsxwing commented on standalone/src/main/java/io/delta/standalone/expressions/Column.java
> +            throw new RuntimeException("Couldn't find matching rowRecord DataType for column: " + name);
Could you complete the code?

2021-09-27 18:54 UTC, zsxwing commented on standalone/src/main/java/io/delta/standalone/expressions/BinaryComparison.java
> +    protected int compare(Object leftResult, Object rightResult) {
How about exposing Comparator to subclasses instead, such as
```
Comparator<Object> getComparator
```
`Comparator` is a pretty common class and subclasses can reuse their existing code/library for comparator.

2021-09-28 16:27 UTC, scottsand-db commented
closing since we have opted to instead merge just a bare-bones `Expression.java` interface (with no child implementations) into master. we will merge a more complete expression framework into master when the framework is in better shape and not just prototype.

2021-09-28 16:27 UTC, closed without merging