Delta configs
delta-io/connectors pull request #164
Opened 2021-10-06 02:53 UTC by allisonport-db

todo:
- add tests
- parse CalendarInterval
- update DeltaRetentionSuite and OptimisticTransactionSuite

2021-10-12 16:34 UTC, scottsand-db requested changes
Awesome work. Left mainly nits, answered the questions I saw, and added some comments in the tests.

2021-10-12 16:34 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/util/CalendarInterval.scala
> +// todo: what privacy do we want?
`private[internal]` is fine - we don't have any APIs that expose this class publicly (and if we did, then this would have to be in Java).

also, this is fine in `internal.util` package. nice job :)

2021-10-12 16:34 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/util/CalendarInterval.scala
> + * three components.
list the three components

2021-10-12 16:34 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/util/CalendarInterval.scala
> +private[internal] class CalendarInterval(val months: Int,
nit: indentation

2021-10-12 16:34 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/util/CalendarInterval.scala
> +    // todo: implement more exactly? not used
yup, since we are overriding this method, we should implement it correctly. it's not used now but we never know if it will be used in the future.

2021-10-12 16:34 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/util/IntervalUtils.scala
> +object IntervalUtils {
nit: `private[internal]`

2021-10-12 16:34 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/DeltaConfig.scala
> +case class DeltaConfig[T](
nit: private[internal]

2021-10-12 16:34 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/DeltaConfig.scala
> +trait DeltaConfigsBase {
nit: private[internal]

2021-10-12 16:34 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/DeltaConfig.scala
> +object DeltaConfigs extends DeltaConfigsBase
nit: private[internal]

2021-10-12 16:34 UTC, scottsand-db commented on standalone/src/test/scala/io/delta/standalone/internal/DeltaConfigSuite.scala
> +    assert(mergedConf.contains("delta.appendOnly") &&
No need for `mergedConf.contains("delta.appendOnly")`. `mergedConf.get("delta.appendOnly")` is a valid call (will not throw exception) regardless of if the key exists or not.

If, for example, you did, `mergedConf("someKey")` then you would want to do a `.contains` check before, since map(key) calls do throw if the key doesn't exist.

2021-10-12 16:34 UTC, scottsand-db commented on standalone/src/test/scala/io/delta/standalone/internal/DeltaConfigSuite.scala
> +    // todo: this is kind of tested in OptimisticTransactionSuite?
thanks for pointing this out. this is fine, keep both tests

2021-10-12 16:34 UTC, scottsand-db commented on standalone/src/test/scala/io/delta/standalone/internal/DeltaConfigSuite.scala
> +    test("parseCalendarInterval") {
nit: indent this back

2021-10-12 16:34 UTC, scottsand-db commented on standalone/src/test/scala/io/delta/standalone/internal/DeltaConfigSuite.scala
> +      mergedConf.get("delta.minWriterVersion") == Some("0"))
can you also check that non-set configs (e.g. tombstone retention) are set to their default values?

2021-10-12 16:34 UTC, scottsand-db commented on standalone/src/test/scala/io/delta/standalone/internal/DeltaConfigSuite.scala
> +  // todo: edge cases for parsing? add test cases?
sure. what happens if a user specifies a non-existent key, or passes in an invalid value?

2021-10-12 16:34 UTC, scottsand-db commented on standalone/src/test/scala/io/delta/standalone/internal/DeltaRetentionSuite.scala
> +          Metadata(configuration = Map("delta.enableExpiredLogCleanup" -> "true")) :: Nil,
nice catch. yeah it is

2021-10-13 00:14 UTC, allisonport-db commented on standalone/src/test/scala/io/delta/standalone/internal/DeltaConfigSuite.scala
> +  // todo: edge cases for parsing? add test cases?
For non-existent keys: Isn't this not an issue until we call `DeltaConfigs.$CONFIG.fromMetaData(metadata)`? In which case we just want the default value (and to ignore the non-existent key)

For invalid values: I'm now realizing we don't validate the value (we don't invoke `apply` right?) But this is how OSS does it, when should we be validating the values?

2021-10-13 00:19 UTC, scottsand-db commented on standalone/src/test/scala/io/delta/standalone/internal/DeltaConfigSuite.scala
> +  // todo: edge cases for parsing? add test cases?
For non-specified keys, yes we just use the default value.

For an invalid key (e.g. `asdf`), I also suppose that is okay too. Since internally we only ever use DeltaConfigs.$CONFIG APIs, we will never use an invalid key.

Doing it the way OSS does it is how we should do it.

2021-10-13 00:38 UTC, allisonport-db commented on standalone/src/main/scala/io/delta/standalone/internal/DeltaConfig.scala
> +  def fromMetaData(metadata: Metadata): T = {
Why is this `fromMetaData` and not `fromMetadata`? Former is copied from OSS, but in connectors all references I've seen have been `Metadata`. Should this be changed to match the rest of the code?

2021-10-13 05:07 UTC, zsxwing commented on standalone/src/main/java/io/delta/standalone/util/ParquetSchemaConverter.java
> +public class ParquetSchemaConverter {
nit: remove this unused file?

2021-10-13 05:09 UTC, zsxwing commented on standalone/src/main/scala/io/delta/standalone/internal/DeltaConfig.scala
> +private[internal] trait DeltaConfigsBase {
You can make this `object DeltaConfigs` directly.

2021-10-13 05:10 UTC, zsxwing commented on standalone/src/main/scala/io/delta/standalone/internal/DeltaConfig.scala
> +      case kv @ (key, value) if key.toLowerCase(Locale.ROOT).startsWith("delta.constraints.") =>
Right. We should throw an error.

2021-10-13 05:15 UTC, zsxwing commented on standalone/src/main/scala/io/delta/standalone/internal/DeltaConfig.scala
> +//        logConsole(
Yep. Logging is pretty helpful for debugging. We can use slf4j similar to https://github.com/delta-io/connectors/blob/master/hive/src/main/scala/io/delta/hive/DeltaInputFormat.scala#L59

2021-10-13 05:18 UTC, zsxwing commented on standalone/src/main/scala/io/delta/standalone/internal/DeltaConfig.scala
> +    // todo: is there a hadoop conf prefix?
In OSS Delta, when a user sets a SQL conf using the prefix `spark.databricks.delta.properties.defaults.` such as `spark.databricks.delta.properties.defaults.randomPrefixLength`, we will set the table property `delta.randomPrefixLength` to this value when creating a table.

We can use the same mechanism here: when a user sets a **Hadoop** conf using the prefix `spark.databricks.delta.properties.defaults.` such as `spark.databricks.delta.properties.defaults.randomPrefixLength`, we will set the table property `delta.randomPrefixLength` to this value when **creating a table**.

2021-10-13 05:19 UTC, zsxwing commented on standalone/src/main/scala/io/delta/standalone/internal/exception/DeltaErrors.scala
> +    // TODO: AnalysisException ?
IllegalArgumentException looks good to me

2021-10-13 05:20 UTC, zsxwing commented on standalone/src/main/scala/io/delta/standalone/internal/util/CalendarInterval.scala
> +  override def hashCode(): Int = {
Since we are in Scala, we can make CalendarInterval be a case class and remove `hashCode` and `equals`.

2021-10-13 17:45 UTC, allisonport-db commented on standalone/src/main/scala/io/delta/standalone/internal/DeltaConfig.scala
> +//        logConsole(
Should I add this now or wait for a future PR?

2021-10-13 19:00 UTC, scottsand-db commented on standalone/src/test/scala/io/delta/standalone/internal/DeltaConfigSuite.scala
> +import org.apache.hadoop.conf.Configuration
small nit: next sprint we will be adding checks or at least style-guide documentation for import order.
so, `org.apache....` imports should come after `io.delta.standalone` imports (separated by 1 line).

But this is fine for now, since I plan on fixing all import orders next sprint. Just an FYI for future work.

2021-10-14 05:38 UTC, merged