Flink Delta Sink 1
delta-io/connectors pull request #196
Opened 2021-11-03 21:44 UTC by pkubit-g

Add base structures for Flink Delta Sink && base implementation for writing Parquet files.
This PR contains base logic for writing DataStream's events into the underlying FileSystem in an idempotent manner.
It behaves very similar to Flink's [FileSink](https://github.com/apache/flink/blob/master/flink-connectors/flink-connector-files/src/main/java/org/apache/flink/connector/file/sink/FileSink.java). The main difference is tightly coupling to the Parquet Format and extending the committables with metadata of the written files.

2021-11-03 23:08 UTC, tdas requested changes
This is a good start. I did a very cursory high-level pass. My major comment is that please add class docs and method docs for every non-trivial method implementation (e.g. ignore getter/setter methods).

The other question I have is style. Is it possible to add the Java style checks? (cc @scottsand-db @zsxwing  is there java style guide in the other standalone module and can that setting be reused?)

2021-11-03 23:37 UTC, scottsand-db commented
@tdas the DSW feature branch adds java checkstyle tests. @pkubit-g would just need to have the github actions run the tests by updating `.github/workflows/test.yaml`

2021-11-09 15:01 UTC, tdas commented on flink-connector/src/main/java/org/apache/flink/connector/delta/sink/DeltaSink.java
> +     *                      *     written to its output
fix

2021-11-10 14:58 UTC, tdas requested changes

2021-11-10 14:58 UTC, tdas commented on flink-connector/src/main/java/org/apache/flink/connector/delta/sink/DeltaSink.java
> +
nit: extra line

2021-11-10 14:58 UTC, tdas commented on flink-connector/src/main/java/org/apache/flink/connector/delta/sink/DeltaSinkBuilder.java
> +
nit: extra line

2021-11-10 14:58 UTC, tdas commented on flink-connector/src/main/java/org/apache/flink/connector/delta/sink/DeltaSinkBuilder.java
> +
nit: extra line

2021-11-10 14:58 UTC, tdas commented on flink-connector/src/main/java/org/apache/flink/connector/delta/sink/DeltaSinkBuilder.java
> +
nit: extra line

2021-11-10 14:58 UTC, tdas commented on flink-connector/src/main/java/org/apache/flink/connector/delta/sink/DeltaSinkBuilder.java
> +
nit: extra line

2021-11-10 14:58 UTC, tdas commented on flink-connector/src/main/java/org/apache/flink/connector/delta/sink/committables/DeltaGlobalCommittableSerializer.java
> +
nit: extra line

2021-11-10 14:58 UTC, tdas commented on flink-connector/src/main/java/org/apache/flink/connector/delta/sink/committer/DeltaCommitter.java
> +    ///////////////////////////////////////////////////////////////////////////
i dont get what is file sink specific here?

2021-11-10 14:58 UTC, tdas commented on flink-connector/src/main/java/org/apache/flink/connector/delta/sink/writer/DeltaWriterBucket.java
> +    // --------------------------- Static Factory -----------------------------
please be consistent in defining regions in the class ... either this way `//-----` here or  `///////` as above for FileSink-specific methods. Personally I prefer the `//////` as its more visible in larger blocks of code.

Please go through all the files to make it consistent

2021-11-10 20:24 UTC, pkubit-g commented on flink-connector/src/main/java/org/apache/flink/connector/delta/sink/committer/DeltaCommitter.java
> +    ///////////////////////////////////////////////////////////////////////////
RIght now nothing. The marker will have more value when i create PR with the implementation as it will be almost the same as in the FileCommitter except custom DeltaSink class members.
Would you see it differently or maybe just `FileSink-specific` comment is unfortunate ?

2021-11-11 22:09 UTC, scottsand-db approved these changes
LGTM! Great work. Just added nits for javadocs. thanks!

2021-11-11 22:09 UTC, scottsand-db commented on flink-connector/src/main/java/org/apache/flink/connector/delta/sink/DeltaSink.java
> + * the commit to the {@link DeltaLog} at the final stage of each checkpoint.
nit bring this up to above line

2021-11-11 22:09 UTC, scottsand-db commented on flink-connector/src/main/java/org/apache/flink/connector/delta/sink/DeltaSink.java
> + * {@link org.apache.flink.connector.file.sink.FileSink} implementation simply by coping the
nit: copying

2021-11-11 22:09 UTC, scottsand-db commented on flink-connector/src/main/java/org/apache/flink/connector/delta/sink/committables/DeltaGlobalCommittableSerializer.java
> + * Versioned serializer for  {@link DeltaGlobalCommittable}.
nit: extra space after `for`

2021-11-11 22:09 UTC, scottsand-db commented on flink-connector/src/main/java/org/apache/flink/connector/delta/sink/writer/DeltaWriterBucketState.java
> + * <a href="https://ci.apache.org/projects/flink/flink-docs-master/docs/learn-flink/"</a>
nit: can you use `@see <a href="URL" target="_blank">Label</a>`

2021-11-11 22:17 UTC, tdas commented on flink-connector/src/main/java/org/apache/flink/connector/delta/sink/DeltaSink.java
> + * application's checkpoints when events are being flushed to files (or appended to writers'
its okay. its understandable in context. but yes, a marginally better term would be "records".

2021-11-11 22:20 UTC, tdas approved these changes
Just address Scott's comments.

2021-11-11 22:20 UTC, tdas commented on flink-connector/src/main/java/org/apache/flink/connector/delta/sink/committer/DeltaCommitter.java
> +    ///////////////////////////////////////////////////////////////////////////
ideally we should put this marker when there is more relevant code in it. but thats okay, i wont block this PR on that since more changes are coming.

2021-11-15 23:25 UTC, pkubit-g commented
@scottsand-db @tdas thank you so much for the review. I've committed the corrections - so far as separate commit to keep it clean for you, but when you accept then i will squash to get only 1 commit per this PR.

2021-11-16 00:01 UTC, tdas commented
we do a squash merge anyways. so dont worry about doing that. all i suggest is making the description a bit better e.g., "Flink Delta Sink - PR 1" because that will become the commit.

2021-11-16 18:09 UTC, merged