Flink Delta Sink - Docs
delta-io/connectors pull request #236
Opened 2021-12-16 01:00 UTC by pkubit-g

2021-12-16 19:16 UTC, tdas commented on flink-connector/README.md
> +- Flink Delta Sink for directly writing data from Apache Flink's applications to a Delta Lake's
```suggestion
- Sink for directly writing data from Apache Flink's applications to a Delta tables
```

2021-12-16 19:17 UTC, tdas commented on flink-connector/README.md
> +- source for reading Delta Lake's table using Apache Flink
```suggestion
- Source for reading Delta Lake's table using Apache Flink (still in progress)
```

2021-12-16 19:39 UTC, tdas commented on flink-connector/README.md
> +if you want to learn more about the internals of the connector.
No need to have this here. Very few people will need this. i added the link in the flink issue. so we can point to the issue. but do it at the end of the doc. maybe have a "Additional Resources" section

2021-12-16 19:41 UTC, tdas commented on flink-connector/README.md
> +            <groupId>io.delta</groupId>
why do you need to explicitly add standalone? that is transitive dependency and should be automatically added.

2021-12-16 19:42 UTC, tdas commented on flink-connector/README.md
> +            <groupId>org.apache.flink</groupId>
again .. these are compile time dependencies .. isnt it? user's shouldnt have to add this unless they want to use a specific version of flink in their application

2021-12-16 19:44 UTC, tdas commented on flink-connector/README.md
> +Scala 2.11:
wait... if flink depends on standalone which is scala-specific....then even if we release a single jar of flink ... we still have to have different sbt configurations for different versions of scala to bring in the necessary scala-specific standalone...isnt it?

2022-01-05 15:55 UTC, tdas commented on flink-connector/README.md
> +Flink Delta Lake Connector is a JVM library to read and write data from Apache Flink applications' to a Delta Lake
this is repeating the intro once again.. consolidate this in the intro section and simplify the building section

2022-01-05 15:55 UTC, tdas commented on flink-connector/README.md
> +## Flink connector
this section header is superfluous. this readme is only for Flink connector so .. why have section here

2022-01-05 15:57 UTC, tdas commented on flink-connector/README.md
> +### How to use it
How to use it should not be a under "Building". It should be a top-level section likee
- Intro
- Usage
- Building

2022-01-05 16:00 UTC, tdas commented on flink-connector/delta_sink_wiki.md
> +### SBT
This is repeated from the README

2022-01-06 19:22 UTC, tdas commented on examples/flink-connector-example-project/pom.xml
> +<?xml version="1.0" encoding="UTF-8"?>
name the directory `flink-example` to reduce length

2022-01-06 20:19 UTC, tdas commented on flink-connector/README.md
> +# Flink Delta Lake Connector
why do you need the above empty directories?

2022-01-09 23:24 UTC, pkubit-g commented on examples/flink-connector-example-project/pom.xml
> +<?xml version="1.0" encoding="UTF-8"?>
done

2022-01-09 23:30 UTC, pkubit-g commented on flink-connector/README.md
> +# Flink Delta Lake Connector
I assume you mean `example_table` and `example_partitioned_table` ?
Those are the directories that the example project uses as target paths for its Delta's tables. 
With every run of the example project (before starting the in-memory Flink job) those dirs are being emptied and recreated so we can easily remove them, but i thought that we may as well leave them in the example dir to explicitly indicate for the users where they should look for created tables and written data/delta log.

2022-01-13 01:09 UTC, scottsand-db requested changes
Minor changes requested

2022-01-13 01:09 UTC, scottsand-db commented on flink-connector/README.md
> +Yes, you can use this connector to append data to either an existing or a new Delta Lake Table (if there is no existing
`Delta Lake table` (lowercase `t`)

2022-01-13 01:09 UTC, scottsand-db commented on flink-connector/README.md
> +as `delta.io.flink.DeltaTablePartitionAssigner`.
can you include a link to the example showing this?

2022-01-13 01:09 UTC, scottsand-db commented on flink-connector/README.md
> +set `shouldTryUpdateSchema` param to true. In such case DeltaStandaloneWriter will try to merge both schemas and check
`Delta Standalone`

2022-01-13 01:09 UTC, scottsand-db commented on flink-connector/README.md
> +commit which will cause failure of the Flink job.
then what? how would users recover from this state?

2022-01-13 01:11 UTC, scottsand-db commented
@tdas since this README.md is going into the `flink-connector/` folder, then an action item for us should be to refactor the root `README.md` for hive and standalone into similar folders.

Then the root README.md should have more general information, with links to WIKIs / docs / other READMEs / Javadocs, eh?

2022-01-14 23:01 UTC, pkubit-g commented
hi @scottsand-db so i was trying to generate the javadocs but it seems like the exclusion rule works in other way than expected. 
My understating was that it should exclude javadocs for the `internal` classes, whereas it seems that it excludes the internal classes and only then tries to compile the code, what fails because included classes try to import those not existing (excluded ones).
![Screenshot from 2022-01-14 23-52-06](https://user-images.githubusercontent.com/91378169/149595605-0cd66890-bf30-4d97-82d8-4b3b8c86bb15.png)

Please let me know if've misintepreted or overlooked something. 
I'm trying to find another solution for this exclusion rule but with no luck yet since the docs for this `unidoc` are very scarce. Or maybe there are sbt tricks that we could use to workaround this ?

2022-01-15 12:41 UTC, pkubit-g commented on examples/flink-example/src/main/java/io/delta/flink/example/sink/DeltaSinkExample.java
> + * Delta table under directory of "/src/main/resources/example_table". The job will be run in a daemon thread while
yep, my bad. Corrected. Thanks!

2022-01-15 12:41 UTC, pkubit-g commented on examples/flink-example/src/main/java/io/delta/flink/example/sink/DeltaSinkExample.java
> + * in the main app's thread there will Delta Standalone Reader application reading and printing all the data to the
corrected

2022-01-15 12:44 UTC, pkubit-g commented on examples/flink-example/src/main/java/io/delta/flink/example/sink/DeltaSinkExampleBase.java
> +        throw new RuntimeException("Not implemented");
my bad, have been switching between different languages lately and i missed the fact that when having abstract class in Java i should not be throwing anything, just make it abstract. Corrected.

2022-01-15 12:44 UTC, pkubit-g commented on examples/flink-example/src/main/java/io/delta/flink/example/sink/DeltaSinkExampleSourceFunction.java
> + * Internal class providing mock implementation for example stream source.
corrected

2022-01-15 12:45 UTC, pkubit-g commented on examples/flink-example/src/main/java/io/delta/flink/example/sink/DeltaSinkPartitionedTableExample.java
> + * Delta table under directory of "/src/main/resources/example_table". The job will be run in a daemon thread while
corrected

2022-01-15 12:47 UTC, pkubit-g commented on examples/flink-example/src/main/java/io/delta/flink/example/sink/DeltaSinkPartitionedTableExample.java
> + * in the main app's thread there will Delta Standalone Reader application reading and printing all the data to the
corrected

2022-01-15 12:47 UTC, pkubit-g commented on flink-connector/README.md
> +tables utilizing [Delta Standalone JVM library](https://github.com/delta-io/connectors). It includes
corrected

2022-01-15 12:48 UTC, pkubit-g commented on flink-connector/README.md
> +tables utilizing [Delta Standalone JVM library](https://github.com/delta-io/connectors). It includes
corrected

2022-01-15 12:48 UTC, pkubit-g commented on flink-connector/README.md
> +- Sink for writing data from Apache Flink to a Delta tables
corrected

2022-01-15 12:48 UTC, pkubit-g commented on flink-connector/README.md
> +  able to read from it,
corrected

2022-01-15 13:03 UTC, pkubit-g commented on flink-connector/README.md
> +commit which will cause failure of the Flink job.
they don't, at least automatically. i believe this is what we have specified and agreed on within the design doc - if the DeltaLog's commit fails because of some sort of schema incompatibility then it cannot be automatically resolved by the connector and we should fail the job to let the user perform a validation.

Are you suggesting that we should put some comment like `such situation may require some manual user's validation in order to retain the table's consistency` ?

2022-01-15 15:23 UTC, pkubit-g commented
hi @tdas @scottsand-db 
so i've corrected the linkage in java docs from root API classes to `internal` package. There where only 4 such cases, all of the other errors are caused by removed sources and it seems like the unidoc plugin tries to compile the module aftere excluding the internal package. Funnily enough it's not the case for the `standalone` module. I've had a quick chat on this with @scottsand-db and he has some smart ideas how to workaround this so i will wait for your expertise on this as i;ve failed when trying to resolve it on my own.

2022-02-03 00:58 UTC, scottsand-db commented on flink-connector/src/main/java/io/delta/flink/sink/DeltaSink.java
> +    private long restoreOrGetNextCheckpointId(List<AbstractDeltaWriterBucketState> states) {
do we need to do this for private methods? those won't be exposed in the javadocs right?

2022-02-03 01:06 UTC, scottsand-db commented on flink-connector/src/main/java/io/delta/flink/sink/internal/writer/DeltaWriter.java
> +        return (List<AbstractDeltaCommittable>) (List<?>) committables;
Can we avoid doing this by doing

```java
List<AbstractDeltaCommittable> committables = new ArrayList<>();
...
committables.addAll(...);
...
return committables;
```

2022-02-03 01:07 UTC, scottsand-db commented on flink-connector/src/test/java/io/delta/flink/sink/utils/DeltaSinkTestUtils.java
> +    public static Sink<RowData, ?, ?, ?> createDeltaSink(String deltaTablePath,
just curious, why doesn't `DeltaSink<RowData>` work?

2022-02-03 01:09 UTC, pkubit-g commented on flink-connector/src/main/java/io/delta/flink/sink/DeltaSink.java
> +    private long restoreOrGetNextCheckpointId(List<AbstractDeltaWriterBucketState> states) {
you're right. I've simply went too far, thanks !

2022-02-03 01:11 UTC, pkubit-g commented on flink-connector/src/main/java/io/delta/flink/sink/internal/writer/DeltaWriter.java
> +        return (List<AbstractDeltaCommittable>) (List<?>) committables;
yeah, should work. 
Tbh i do not have a preference which is better - casting or creating duplicated list so can change this.
Out of curiosity - is there any specific reason for proposing this besides code style ?

2022-02-03 01:12 UTC, pkubit-g commented on flink-connector/src/test/java/io/delta/flink/sink/utils/DeltaSinkTestUtils.java
> +    public static Sink<RowData, ?, ?, ?> createDeltaSink(String deltaTablePath,
it's a leftover from previous prototyping. 
I haven't done a second pass on all the changes in the PR yet, will do it tomorrow.

2022-02-03 01:15 UTC, pkubit-g commented
@scottsand-db 
you're quick :) In between i got stuck with rebasing this branch on top of current master as there were some tricky conflicts and only now i'm pushing rebased version. You can take a look at this once again if you wish, however i do need to take a detailed pass on the whole PR once again tomorrow to make sure that i've resolved all the conflicts correctly.

2022-02-03 14:50 UTC, pkubit-g commented
@cheleb could you take a look at failing checks in this PR ? I've rebased it on top of master and now the build is failing with some weird error and it looks like [this commit](https://github.com/delta-io/connectors/commit/416a3d593d254e11d444f9c60ba71cec93d6739f) may have sth to do with it.

2022-02-03 14:58 UTC, pkubit-g commented on flink-connector/src/main/java/io/delta/flink/sink/internal/writer/DeltaWriter.java
> +        return (List<AbstractDeltaCommittable>) (List<?>) committables;
@scottsand-db after giving it a second thought i would say that casting here is better than rewritting whole collection, isn't it?

2022-02-03 16:59 UTC, scottsand-db commented on flink-connector/src/main/java/io/delta/flink/sink/internal/writer/DeltaWriter.java
> +        return (List<AbstractDeltaCommittable>) (List<?>) committables;
Where is the duplicate collection? We create `committables` .... then we add to it .... then we return it.

Let me know what I am missing.

2022-02-03 17:41 UTC, pkubit-g commented on flink-connector/src/main/java/io/delta/flink/sink/internal/writer/DeltaWriter.java
> +        return (List<AbstractDeltaCommittable>) (List<?>) committables;
with this solution we need to allocate new ArrayList instance which will contain the same elements as the initial one, so the casting will come with a slightly smaller cost. 
I'm not saying that this "cost" is an argument here, however i do not see what we would gain if we go for new ArrayList allocation instead of explicit casting.

2022-02-03 18:10 UTC, cheleb commented
> @cheleb could you take a look at failing checks in this PR ? I've rebased it on top of master and now the build is failing with some weird error and it looks like [this commit](https://github.com/delta-io/connectors/commit/416a3d593d254e11d444f9c60ba71cec93d6739f) may have sth to do with it.

genjavadoc plugin should be updated ?

2022-02-03 18:58 UTC, kristoffSC commented on flink-connector/src/main/java/io/delta/flink/sink/internal/writer/DeltaWriter.java
> +        return (List<AbstractDeltaCommittable>) (List<?>) committables;
I strongly suggest casting over creating a new array. 

Actually I would say that casting here has almost zero cost.
I believe we do Implicit casting, meaning casting from a type to a wider type, which is done automatically and there is no overhead.

DeltaCommittable -> AbstractDeltaCommittable, plus this is all Generics so in the runtime List<AbstractDeltaCommittable> becomes List<Object> anyways.

2022-02-03 19:29 UTC, scottsand-db commented on flink-connector/src/main/java/io/delta/flink/sink/internal/writer/DeltaWriter.java
> +        return (List<AbstractDeltaCommittable>) (List<?>) committables;
Sorry, I don't think you've answered my root question of "where is this duplicate collection?". How does my approach "Create a new array"?

From what I understand, your approach does
```java
List<DeltaCommittable> committables = new ArrayList<>();
...
while (activeBucketIter.hasNext()) {
    ...
        committables.addAll(entry.getValue().prepareCommit(flush, appId, nextCheckpointId));
    ...
}
...
return (List<AbstractDeltaCommittable>) (List<?>) committables;
```

and my approach does this
```java
List<AbstractDeltaCommittable> committables = new ArrayList<>(); // ****** use Abstract ******
...
while (activeBucketIter.hasNext()) {
    ...
        committables.addAll(entry.getValue().prepareCommit(flush, appId, nextCheckpointId));
    ...
}
...
return committables; // ****** no casting ******
```

I just don't see where the duplicate array is coming from. There's still only one `ArrayList`. Let me know.

2022-02-03 19:31 UTC, scottsand-db commented on flink-connector/src/main/java/io/delta/flink/sink/internal/writer/DeltaWriter.java
> +        return (List<AbstractDeltaCommittable>) (List<?>) committables;
> Out of curiosity - is there any specific reason for proposing this besides code style ?
This is purely a code style suggestion

2022-02-03 20:13 UTC, kristoffSC commented on flink-connector/src/main/java/io/delta/flink/sink/internal/writer/DeltaWriter.java
> +        return (List<AbstractDeltaCommittable>) (List<?>) committables;
Hah,
I think there was a misunderstanding :)

In that code snipped you added to your comment, it looked like you would like to create a new Array, 
where in fact you just changed the generic type in already existing Array.

So in that case, I would be voting to chanign the original, existing array declaration from:
`List<DeltaCommittable> committables = new ArrayList<>();`
to
`List<AbstractDeltaCommittable> committables = new ArrayList<>(); // ****** use Abstract ******`

2022-02-03 20:18 UTC, scottsand-db commented on flink-connector/src/main/java/io/delta/flink/sink/internal/writer/DeltaWriter.java
> +        return (List<AbstractDeltaCommittable>) (List<?>) committables;
Ah, that makes more sense.
So yeah, I prefer `List<AbstractDeltaCommittable> committables = new ArrayList<>(); // ****** use Abstract ******` instead of casting.

2022-02-03 21:25 UTC, pkubit-g commented on flink-connector/src/main/java/io/delta/flink/sink/internal/writer/DeltaWriter.java
> +        return (List<AbstractDeltaCommittable>) (List<?>) committables;
oh my ...
@scottsand-db you're absolutely right and thank you for spotting this as i've missed this detail during refactor.

And yeah, the misunderstanding was that creating a separate array is an alternative solution to casting, but obviously only when the collection is passed as an method's arguments, eg.
```
def someMethod(List<Committable> committables) {

    List<AbstractDeltaCommittable> abstractCommittables = new ArrayList<>();
    abstractCommittables.addAll(committables);
    
    // same effect:
    (List<AbstractDeltaCommittable>) (List<?>) committables
```    
So that's why i thought you are suggesting the former instead of the latter. But obviously both solutions doesn't apply when we are creating the collection inside the method, so thank you for "finger-pointing" the suggestion :) 


FYI i'm moving this part to a separate PR as discussed and will include this fix in there.

2022-02-03 22:10 UTC, pkubit-g commented
@cheleb this has done the trick, thank you !

2022-02-08 17:10 UTC, merged