Flink Delta Sink - PR 7
delta-io/connectors pull request #239
Opened 2021-12-16 18:51 UTC by pkubit-g

In this PR:
- `flink-connector`'s dependencies are being marked as "provided",
- `flink-connector`'s packages are being renamed `org.apache.flink.connector.delta.sink` -> `io.delta.flink.sink`

2021-12-16 22:55 UTC, tdas requested changes
I think we should have separate packages for the public API classes (like Builder and Sink) and the internal classes (committers and committables). This would allows us to only put the public class package in Java docs.... and hide all the internal classes by hiding the entire package from the java docs.

2021-12-17 14:44 UTC, pkubit-g commented
@tdas do you have a preference whether we should use exclude or include condition for docs generator plugin ?
If no then i can simply put all of nested packages under `internal` and you will be able to put exlusion for `io.delta.flink.sink.internal` package. Sounds good ? I'm committing this right know for reference so take a look and let me know if you see it differently. Also i'm not sure about `SchemaConverter` class so leaving it as is which means top-level, but if you think that this should go to internal as well then let me know.

2021-12-17 15:29 UTC, tdas commented
that is usually how we do it in other places. internal as the package name sounds good. that makes it very obvious independent of the java docs that these classes are not public.

the schema converter is not something that the users have to directly use in any way.... isnt it? if not, then make it internal.

2021-12-17 15:44 UTC, pkubit-g commented
@tdas yeah, given a second thought i agree with "hiding" SchemaConverter as well. Done && committed.
![Screenshot from 2021-12-17 16-43-26](https://user-images.githubusercontent.com/91378169/146570447-3f1034ae-7b54-49b6-8841-d28d2ddae3db.png)

2021-12-17 17:18 UTC, tdas commented on build.sbt
> +        s"""package io.delta.flink.sink;
this does not need to be in thee public package.. isnt it?

2021-12-17 17:46 UTC, pkubit-g commented on build.sbt
> +        s"""package io.delta.flink.sink;
well, that's a good catch. Changed.

2021-12-17 18:03 UTC, tdas commented on build.sbt
> +      "org.apache.flink" %% "flink-table-runtime-blink" % flinkVersion % "provided",
do we need all of these for compile time?

2021-12-17 18:55 UTC, pkubit-g commented on build.sbt
> +      "org.apache.flink" %% "flink-table-runtime-blink" % flinkVersion % "provided",
that's my bad. I thought i verified this some time ago but i may have some protyped code in the project that time, sorry for this.

I have narrowed it down and removed `flink-runtime`  and `flink-streaming-java % test`. Also i've changed scope for `flink-table-runtime-blink` from `provided` to `test`.

I will also adjust the docs and readme branch accordingly.

2021-12-17 19:16 UTC, pkubit-g commented on build.sbt
> +      "org.apache.flink" %% "flink-table-runtime-blink" % flinkVersion % "provided",
@tdas tests went good, can you double check if the current state of build.sbt resolves your concerns ?

2021-12-17 23:46 UTC, tdas approved these changes

2021-12-17 23:47 UTC, merged