Fail when committing metadata with incorrect protocol update
delta-io/connectors pull request #242
Opened 2021-12-20 19:27 UTC by allisonport-db

Resolves #229 

Should we throw an error if protocol configuration properties are provided, but they are correct?

2021-12-20 19:34 UTC, scottsand-db commented
> Should we throw an error if protocol configuration properties are provided, but they are correct?

Good question. We shouldn't throw an error in this case.

2021-12-20 22:14 UTC, scottsand-db requested changes
Left a couple of comments + questions

2021-12-20 22:14 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/OptimisticTransactionImpl.scala
> +      finalActions = newProtocol.toSeq ++ finalActions
doesn't this mean we are double-adding the Protocol action?

```scala
val protocolOpt = finalActions.collectFirst{ case p: Protocol => p } // extract Protocol from finalActions list
...
finalActions = newProtocol.toSeq ++ finalActions // add Protocol back into the finalActions list
```

2021-12-20 22:14 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/OptimisticTransactionImpl.scala
> +    newMetadata.foreach{ m =>
nit: ` {` (spacing)

2021-12-20 22:14 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/OptimisticTransactionImpl.scala
> -      "Cannot change the metadata more than once in a transaction.")
since we are removing this assertion, can you please update the scaladoc of this method stating that the caller must ensure no Metadata action is being passed inside of `actions` ?

2021-12-20 22:14 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/OptimisticTransactionImpl.scala
> +      return
so if the user passes in two identical Metadata, we will take the first one only and not throw an exception.

can you add a test for this? (this is a weird case, but a test case makes it explicit)

For example, at first pass I was confused why the test case copied here was passing, but it is because each Metadata() has a different created at time.

```
test("commits shouldn't have more than one Metadata") {
    withTempDir { dir =>
      val log = DeltaLog.forTable(new Configuration(), dir.getCanonicalPath)
      val txn = log.startTransaction()
      val e = intercept[AssertionError] {
        txn.commit(Metadata() :: Metadata() :: Nil, manualUpdate, engineInfo)
      }
      assert(e.getMessage.contains("Cannot change the metadata more than once in a transaction."))
    }
  }
```

Can you also please update this test case name since it is no longer accurate

2021-12-20 22:14 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/OptimisticTransactionImpl.scala
> -      case (Protocol.MIN_READER_VERSION_PROP, _) => false
can you remind me, what are the consequences of not removing this configuration?

we will still fail later, right? so it won't be committed?

I'm worried that removing this code can mean that we forget to add it back later to Delta Standalone, when we do support multiple protocol versions.

2021-12-20 22:14 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/OptimisticTransactionImpl.scala
> +  private var newMetadataJ: Option[MetadataJ] = None
This seems very coupled to `newMetadata`. i.e. if one is None, the other should be, too.

also, i think we can get rid of it? inside of `updateMetadata` we already convert MetadataJ to Metadata, right? `var latestMetadata = ConversionUtils.convertMetadataJ(metadataJ)`

Couldn't we just perform the Metadata checks then? Let me know if I'm missing something.

2021-12-20 23:32 UTC, allisonport-db commented on standalone/src/main/scala/io/delta/standalone/internal/OptimisticTransactionImpl.scala
> +      finalActions = newProtocol.toSeq ++ finalActions
Err `newProtocol` is only defined if it's a new table (see `updateMetadata`). But this is actually repetitive with 250-262. I think it makes sense to remove the protocol creation in `updateMetadata` and not use `newProtocol` at all.

2021-12-20 23:35 UTC, allisonport-db commented on standalone/src/main/scala/io/delta/standalone/internal/OptimisticTransactionImpl.scala
> -      "Cannot change the metadata more than once in a transaction.")
This assertion is enforced by multiple calls to `updateMetadata` (it will fail the second time it's called.) Re: #229  the issue conversation we decided to accept `Metadata`s in `commit`

2021-12-20 23:37 UTC, allisonport-db commented on standalone/src/main/scala/io/delta/standalone/internal/OptimisticTransactionImpl.scala
> -      case (Protocol.MIN_READER_VERSION_PROP, _) => false
We won't fail later. The check is in `verifyNewMetadata`, if we remove these it won't fail. I will update that method to accept the correct protocol configurations, and then that would be where later updates would go for future version support.

2021-12-20 23:44 UTC, allisonport-db commented on standalone/src/main/scala/io/delta/standalone/internal/OptimisticTransactionImpl.scala
> +      return
So right now it's only accepting the **same** metadata instance (it's checking for reference equality, which is why we're saving the java metadata). Do you think it's more correct to accept equivalent Metadata actions?

For context, this was in theory to accommodate for something like
```
Metadata newMetadata = .....
txn.updateMetadata(newMetadata)
List<Action> actions = .... // generate actions including newMetadata
txn.commit(actions, ....)
```

2021-12-20 23:44 UTC, allisonport-db commented on standalone/src/main/scala/io/delta/standalone/internal/OptimisticTransactionImpl.scala
> +  private var newMetadataJ: Option[MetadataJ] = None
See below (for reference vs object equality)

2021-12-21 14:56 UTC, scottsand-db requested changes
Responded to comments + asked some questions

2021-12-21 14:56 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/OptimisticTransactionImpl.scala
> -      "Cannot change the metadata more than once in a transaction.")
Yup, the assertion enforcement is fine, but I'm wondering if it is clear to future developers how it is that at most one metadata can be committed.

Perhaps add a comment to `updateMetadata` that all metadatas (either directly or extracted from commit actions) must go through that method?

But if you think it's fine, then SGTM.

2021-12-21 14:56 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/OptimisticTransactionImpl.scala
> +      return
I see. I guess my question is, why check for reference equality instead value equality? If two different Metadata actions are value-equivalent, then the same JSON will be written to the delta log, which is all that matters.

So I think that value-equality is fine here.

And this will still work for your code example given above

2021-12-21 14:56 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/OptimisticTransactionImpl.scala
> -      case (Protocol.MIN_READER_VERSION_PROP, _) => false
> that would be where later updates would go for future version support

But why shift this check from here to that function? If Delta OSS and DBR both perform similar checks in this method, what do we gain from moving checks there?

2021-12-21 18:00 UTC, allisonport-db commented on standalone/src/main/scala/io/delta/standalone/internal/OptimisticTransactionImpl.scala
> -      case (Protocol.MIN_READER_VERSION_PROP, _) => false
This isn't a check though, it's filtering out those properties. The check has always been in `verifyNewMetadata` and our issue with not failing was because we were filtering out those properties before. In delta OSS all metadata goes through `verifyNewMetadata` in both `prepareCommit` and `updateMetadata`

2021-12-21 18:01 UTC, allisonport-db commented on standalone/src/main/scala/io/delta/standalone/internal/OptimisticTransactionImpl.scala
> +      return
I think that's fair then sg

2021-12-21 18:03 UTC, allisonport-db commented on standalone/src/main/scala/io/delta/standalone/internal/OptimisticTransactionImpl.scala
> -      "Cannot change the metadata more than once in a transaction.")
I'll add a comment

2021-12-21 20:29 UTC, scottsand-db approved these changes
LGTM with 1 indentation nit / comment

2021-12-21 20:29 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/OptimisticTransactionImpl.scala
> +   * - Checks for unenforceable NOT NULL constraints in the table schema.
Do you mean to have 3 levels of indentation?
```
* - ...
*  - ...
*    - ...
```

2021-12-21 22:31 UTC, merged