[WIP] Implement "get version at time X" APIs
delta-io/connectors pull request #346
Opened 2022-05-25 23:38 UTC by scottsand-db

This PR adds two new APIs
- `long getVersionBeforeOrAtTime(long timestamp)`
- `long getVersionAtOrAfterTime(long timestamp)`

The latter is used to provide the "streaming" semantics needed for the Delta/Flink connector. Specifically, this means that when using the "startingTimestamp" option for a streaming/continuous query, we return the commit version "at or after" that timestamp.

The result of this method (`getVersionAtOrAfterTime`) can then be passed to `DeltaLog::getSnapshotForVersionAsOf` to get the metadata for a particular version, and to `DeltaLog::getChanges` to get the changes from a particular version, for the version corresponding to the input timestamp.

This is different from the "batch" semantics, where for options like "timestampAsOf" we use the snapshot version "at or before" that timestamp.

2022-05-25 23:54 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/DeltaHistoryManager.scala
> +      canReturnLastCommit: Boolean = false,
this defaults introduce no new behaviour to existing usage in `SnapshotManagement::getSnapshotForTimestampAsOf`

2022-05-25 23:54 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/DeltaHistoryManager.scala
> +  def getEarliestDeltaFile(deltaLog: DeltaLogImpl): Long = {
copied from Runtime.

2022-05-25 23:55 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/DeltaHistoryManager.scala
> +  def getEarliestDeltaFile(deltaLog: DeltaLogImpl): Long = {
copied pretty much verbatim from Delta OSS (just added a variable instead of doing it inline).

2022-05-25 23:55 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/DeltaLogImpl.scala
> +      // e.g. we give time T-1 and first commit has time T, then do not want that earliest commit
nit: `NOT` instead of `not`.

2022-05-27 22:28 UTC, zsxwing commented on standalone/src/main/java/io/delta/standalone/DeltaLog.java
> +    long getVersionBeforeOrAtTime(long timestamp);
It's better to call it either `getVersionBeforeOrAt` or `getVersionBeforeOrAtTimestamp`. I prefer `getVersionBeforeOrAtTimestamp`.

2022-06-07 22:32 UTC, allisonport-db reviewed
Minor comments. Mostly clarify documentation, and two questions about testing.

2022-06-07 22:32 UTC, allisonport-db commented on standalone/src/main/scala/io/delta/standalone/internal/DeltaHistoryManager.scala
>     * Returns the latest commit that happened at or before `time`.
Can we just improve the docs to this function? I didn't understand how all the parameters affected the output without reading the code.

A) Improve this general doc, since isn't `Returns the latest commit that happened at or before time.` no longer true?
B) canReturnLastCommit - this was a little confusing since the original documentation doesn't really clearly mention that this function will not return the current (aka latest) commit version and would instead throw an error. I think if that is clarified above this specific param doc is okay.
C) canReturnEarliestCommit - this is confusing the way it's phrased. This is if the timestamp is before the first commit of the table correct? If so, we return that first commit. Is there any other scenario where this parameter affects the return value? If not, can we just specifically say this is what it is, ie. "if the provided timestamp is before the first commit of the table return that first commit" or something along those lines?
D) Can we improve the docs for `@throws IllegalArgumentException`? It's confusing... Especially with respect to the two new parameters. This would also be more clear with the added docs about not returning the latest commit version (see B)

2022-06-07 22:32 UTC, allisonport-db commented on standalone/src/test/scala/io/delta/standalone/internal/DeltaLogSuite.scala
> +  test("getVersionBeforeOrAtTime and getVersionAtOrAfterTime") {
What happens for a delta table that hasn't been committed yet? Should it be the `FileNotFound` exception I'm seeing or should we see the `IllegalArgumentException` mentioned in the docs?

2022-06-07 22:32 UTC, allisonport-db commented on standalone/src/test/scala/io/delta/standalone/internal/DeltaLogSuite.scala
> +  test("getVersionBeforeOrAtTime and getVersionAtOrAfterTime") {
Can we test that these functions don't care if that version is reproducible or not?

2022-06-08 00:53 UTC, tdas commented on standalone/src/main/scala/io/delta/standalone/internal/DeltaHistoryManager.scala
> +      canReturnLastCommit: Boolean = false,
you have now 3 booleans, which is 2^3 = 8 combination of input params. do you need all of them? if not why add so much complexity. why not just implement the exact 2-3 versions that you need. is that hard?

2022-06-08 01:02 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/DeltaHistoryManager.scala
> +      canReturnLastCommit: Boolean = false,
So we need:
- `getVersionBeforeOrAtTimestamp` uses (true, false, false)
- `getVersionAtOrAfterTimestamp` uses (false, false, true)
- `SnapshotManagement::getSnapshotForTimestampAsOf` uses all defaults, which is (false, true, false)

As you can see, we do use true/false values for all 3 booleans.

Also, sure, there are 8 combinations of the booleans, but they are only used for exclusive scenarios
- `mustBeRecreatable` is a must-have, and has no impact on `canReturnEarliestCommit` or `canReturnLastCommit`
- `canReturnEarliestCommit` is only relevant if `commit.timestamp > time`
- `canReturnLastCommit` is only relevant if `commit.timestamp < time`

Thus, the combination of `canReturnEarliestCommit` and `canReturnLastCommit` have no impact on one another.

Also, this is just copying what Delta Lake does [here](https://github.com/delta-io/delta/blob/master/core/src/main/scala/org/apache/spark/sql/delta/DeltaHistoryManager.scala#L113-L117). This means we've circled back around to the question of: do we copy what Delta Lake does, and make debugging errors more consistent or easier, or do something different? I prefer copying what Delta Lake does. Plus, in this code, I think this code makes sense.

Let me know what you think.

2022-06-08 01:12 UTC, tdas commented on standalone/src/test/scala/io/delta/standalone/internal/DeltaLogSuite.scala
> +      new File(logDir, delta0.getName).setLastModified(nowEpochMs)
i think its easier to read the test if you actually use constants. like `10000`, `20000`, `30000`

2022-06-08 01:19 UTC, tdas requested changes
i am not sure of the complexity of the param list

2022-06-08 02:15 UTC, tdas commented on standalone/src/main/scala/io/delta/standalone/internal/DeltaHistoryManager.scala
> +      canReturnLastCommit: Boolean = false,
oh i see. the existing code is already messy, and we are copying from it. thanks for clarifying that. i dont quite like it, but in the interest of consistency, I am okay with this. however lets improve the docs further as @allisonport-db has also commented.

2022-06-09 15:30 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/DeltaHistoryManager.scala
> -  def getActiveCommitAtTime(timestamp: Timestamp): Commit = {
good question. we use this because Delta Lake uses `Timestamp`.

2022-06-09 15:31 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/DeltaHistoryManager.scala
> -  def getActiveCommitAtTime(timestamp: Timestamp): Commit = {
we can refactor this later if we chose

2022-06-09 22:29 UTC, scottsand-db commented on standalone/src/test/scala/io/delta/standalone/internal/DeltaLogSuite.scala
> +  test("getVersionBeforeOrAtTime and getVersionAtOrAfterTime") {
done

2022-06-10 17:40 UTC, allisonport-db approved these changes
LGTM

2022-06-10 17:40 UTC, allisonport-db commented on standalone/src/test/scala/io/delta/standalone/internal/DeltaLogSuite.scala
> +      val TIME_PAST_END = nowEpochMs + 3.minutes
Btw, I think @tdas comment here was to just use actual number constants and not have these variables.

2022-06-10 18:45 UTC, scottsand-db commented on standalone/src/test/scala/io/delta/standalone/internal/DeltaLogSuite.scala
> +      val TIME_PAST_END = nowEpochMs + 3.minutes
darn, i see. thanks!

2022-06-10 18:52 UTC, scottsand-db commented on standalone/src/test/scala/io/delta/standalone/internal/DeltaLogSuite.scala
> +      val TIME_PAST_END = nowEpochMs + 3.minutes
updated.

2022-06-10 19:56 UTC, merged