[delta-standalone] Add check that schema contains partition columns
delta-io/connectors pull request #353
Opened 2022-05-31 20:16 UTC by scottsand-db

This PR adds a check to OptimisticTransaction to ensure that metadata schemas actually contain the metadata partition columns. We also check that there is at least one non-partition column. This check is typically performed in TransactionalWrite (in Delta Lake) [here](https://github.com/delta-io/delta/blob/master/core/src/main/scala/org/apache/spark/sql/delta/files/TransactionalWrite.scala#L138-L151)

Before this fix, it was perfectly possible to write `schema={col1, col2}` and `partitionCols={part1, part2}` (partitions not a subset of schema).
It was also perfectly possible to write `schema={part1, part2}` and `partitionCols={part1, part2}` (no data columns).

The first commit adds the actual relevant code: 49c052dd045da281739bff3c4b7f67093b276eef.

The next commits iteratively fix all of the tests that were broken.

Currently, some flink tests are still failing. I've asked @pkubit-g to regenerate the resource tables, but this time ensuring that the schema contains the partitionCols.

2022-05-31 23:44 UTC, scottsand-db commented
cc @kristoffSC

2022-06-01 00:45 UTC, tdas commented on standalone/src/main/scala/io/delta/standalone/internal/OptimisticTransactionImpl.scala
> +    checkPartitionColumns(latestMetadata.partitionColumns, latestMetadata.schema)
why is this check not already part of the function `verifyNewMetadata` which seem to verify all of the metadata, including schema?

2022-06-01 00:46 UTC, tdas commented on standalone/src/main/scala/io/delta/standalone/internal/exception/DeltaErrors.scala
> +  def nonPartitionColumnAbsentException(): Throwable = {
why absent for one error and not found for the other error?

2022-06-01 00:48 UTC, tdas requested changes
- few minor comments
- in addition, are there checks that all the fileactions have specified all the partition column values?

2022-06-01 00:48 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/exception/DeltaErrors.scala
> +  def nonPartitionColumnAbsentException(): Throwable = {
just following what Delta Lake is currently using.
I advocate for keeping method names the same when we can. It makes searching them up in the two code bases easier.

2022-06-01 00:50 UTC, scottsand-db commented
@tdas 

> are there checks that all the fileactions have specified all the partition column values?

Yes. We check that here
https://github.com/delta-io/connectors/blob/master/standalone/src/main/scala/io/delta/standalone/internal/OptimisticTransactionImpl.scala#L281

2022-06-01 00:51 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/OptimisticTransactionImpl.scala
> +    checkPartitionColumns(latestMetadata.partitionColumns, latestMetadata.schema)
it can be. as I responded on your other comment, I do try and keep the method names between delta-standalone and delta-lake as similar, or identical, as possible. this helps in debugging the code (e.g. if a bug arises in delta-lake, similar code and method names in delta-standalone will make it easier to fix here, too).

what do you think?

2022-06-08 00:55 UTC, tdas commented on flink/src/test/java/io/delta/flink/sink/DeltaSinkBatchExecutionITCase.java
> +        assertEquals(2, initialDeltaFiles.size());
why this change?

2022-06-08 09:06 UTC, kristoffSC commented on flink/src/test/java/io/delta/flink/sink/DeltaSinkBatchExecutionITCase.java
> +        assertEquals(2, initialDeltaFiles.size());
Hi,
I can take this one, since this is my change. 
`assertEqual` API is ` assertEqual(expected, actual).
 
Originally it was the other way around, so our "actual" result was used as "expected" value in assertion. That resulted with confusing assert message if test failed.
 
 There is some inconsistency between Junit API and other libraries that provides assert methods :)
`

2022-06-10 11:26 UTC, tdas approved these changes
i am good  with the prod code changes as long as @kristoffSC has reviewed all test code

2022-06-10 20:12 UTC, kristoffSC commented
@tdas 
All changes in Flink connector tests are actually mine, merged into Scott's PR from this:
https://github.com/scottsand-db/connectors/pull/46

2022-06-10 22:20 UTC, allisonport-db commented on standalone/src/main/scala/io/delta/standalone/internal/OptimisticTransactionImpl.scala
> +    }
Minor thought, this could instead check that `partitionCols` is a subset of `schemaCols`, then our error can list all missing partition columns instead of just one by one, if there were more than 1 omitted from the schema.

This is a minor nit, no biggie either way.

2022-06-10 22:20 UTC, allisonport-db commented on standalone/src/test/scala/io/delta/standalone/internal/OptimisticTransactionLegacySuite.scala
> +      log0.startTransaction().commit(metadata_2 :: add :: Nil, manualUpdate, engineInfo)
why is this one `metadata_2`?

2022-06-10 22:20 UTC, allisonport-db commented on standalone/src/test/scala/io/delta/standalone/internal/OptimisticTransactionLegacySuite.scala
> +        tx1.updateMetadata(metadataJ_2)
Isn't this conceptually changing the test? Previously it wasn't changing the table schema.

2022-06-10 22:34 UTC, scottsand-db commented on standalone/src/test/scala/io/delta/standalone/internal/OptimisticTransactionLegacySuite.scala
> +        tx1.updateMetadata(metadataJ_2)
I could keep `metadataJ`, and the test still passes, but I think it's better to test two conflicting schemas instead.

2022-06-10 22:34 UTC, scottsand-db commented on standalone/src/test/scala/io/delta/standalone/internal/OptimisticTransactionLegacySuite.scala
> +        tx1.updateMetadata(metadataJ_2)
but I'm easy.

2022-06-10 22:34 UTC, scottsand-db commented on standalone/src/test/scala/io/delta/standalone/internal/OptimisticTransactionLegacySuite.scala
> +      log0.startTransaction().commit(metadata_2 :: add :: Nil, manualUpdate, engineInfo)
I can change it to `metadataJ`.

2022-06-10 22:37 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/OptimisticTransactionImpl.scala
> +    }
sgtm

2022-06-10 22:38 UTC, allisonport-db commented on standalone/src/test/scala/io/delta/standalone/internal/OptimisticTransactionLegacySuite.scala
> +        tx1.updateMetadata(metadataJ_2)
I mean I think the failure with updating the same metadata is the more extreme version of the test. Like I'd assume if that throws an error, two different metadatas would. Not sure the same can be said for vice-versa

2022-06-10 22:54 UTC, scottsand-db commented on standalone/src/test/scala/io/delta/standalone/internal/OptimisticTransactionLegacySuite.scala
> +        tx1.updateMetadata(metadataJ_2)
Hm. You could easily argue though that two concurrent txns that update with the exact same metadata shouldn't throw an error.

2022-06-10 22:54 UTC, scottsand-db commented on standalone/src/test/scala/io/delta/standalone/internal/OptimisticTransactionLegacySuite.scala
> +        tx1.updateMetadata(metadataJ_2)
I'll just do both :)

2022-06-10 23:01 UTC, allisonport-db commented on standalone/src/test/scala/io/delta/standalone/internal/OptimisticTransactionLegacySuite.scala
> +        tx1.updateMetadata(metadataJ_2)
i agree.. but then were testing incorrect behavior and should change the impl :/

2022-06-13 21:35 UTC, allisonport-db commented on standalone/src/main/scala/io/delta/standalone/internal/OptimisticTransactionImpl.scala
> +    val partitionsColsNotInSchema = partitionCols.toSet.diff(schemaCols).toSeq
Should we be concerned about performance for tables with many many columns? I.e. we could do `schemaCols.toSet.subset(partitionCols)`

I'm thinking it's not at a scale where it's a big deal.

2022-06-13 21:35 UTC, allisonport-db commented on standalone/src/test/scala/io/delta/standalone/internal/DeltaLogSuite.scala
> +          log.startTransaction().updateMetadata(metadata)
nit: `.commit()` (previous test does this, I'm neutral on whether it's needed)

2022-06-13 21:35 UTC, allisonport-db commented on standalone/src/test/scala/io/delta/standalone/internal/DeltaLogSuite.scala
> +      (correctPartitionsCols, Nil), // equal to
what is this equal to?... isn't the schema columns [part_1, part_2, foo, bar]?

I'm not sure how this is different than the following test.

2022-06-13 21:39 UTC, scottsand-db commented on standalone/src/test/scala/io/delta/standalone/internal/DeltaLogSuite.scala
> +      (correctPartitionsCols, Nil), // equal to
My intention was that `part_1` and `part_2` are the partition columns, hence `correctPartitionsCols`.

So we have cases like
- correctPartitionsCols ==> which is "equal to" correctPartitionsCols
- `Seq("part_1")` ==> which is a subset of correctPartitionsCols

I'll make this more explicit.

2022-06-13 21:39 UTC, scottsand-db commented on standalone/src/test/scala/io/delta/standalone/internal/DeltaLogSuite.scala
> +          log.startTransaction().updateMetadata(metadata)
it's not needed. we verify the metadata in `updateMetadata`

2022-06-13 21:45 UTC, allisonport-db commented on standalone/src/test/scala/io/delta/standalone/internal/DeltaLogSuite.scala
> +      (correctPartitionsCols, Nil), // equal to
But isn't those being the correctPartitionsCols just arbitrary? Like for `(Seq("part_1"), Nil)` why isn't `correctPartitionCols=Seq("part_1")`

2022-06-13 21:46 UTC, allisonport-db commented on standalone/src/test/scala/io/delta/standalone/internal/DeltaLogSuite.scala
> +          log.startTransaction().updateMetadata(metadata)
yeah I was just thinking we don't externally "know" this / what if it was changed in the future

2022-06-13 21:53 UTC, scottsand-db commented on standalone/src/test/scala/io/delta/standalone/internal/DeltaLogSuite.scala
> +          log.startTransaction().updateMetadata(metadata)
if it was changed in the future, then the test will fail, which is what we want. then we know we need to update the code or fix the test.

2022-06-13 22:26 UTC, merged

2022-06-13 22:31 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/OptimisticTransactionImpl.scala
> +    val partitionsColsNotInSchema = partitionCols.toSet.diff(schemaCols).toSeq
do you mean, "calculate the `diff` only if `.subset` is false"?

sorry, little confused because a) schemaCols is already a set, b) `.subset` method doesnt exist, and c) if you mean `.subsetOf`, we want "is partitionsCols a subset of schemaCol", not the other way around.

2022-06-13 22:31 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/OptimisticTransactionImpl.scala
> +    val partitionsColsNotInSchema = partitionCols.toSet.diff(schemaCols).toSeq
but ya, all these set operations are happening in-memory with a few thousand columns at most. I'm not concerned about performance here.

2022-06-13 22:33 UTC, allisonport-db commented on standalone/src/main/scala/io/delta/standalone/internal/OptimisticTransactionImpl.scala
> +    val partitionsColsNotInSchema = partitionCols.toSet.diff(schemaCols).toSeq
> do you mean, "calculate the `diff` only if `.subset` is false"?

yep

Yeah I meant other way around with `subsetOf`. I agree it doesn't matter :)