Standalone: Implement actions iterator from `VersionLog`
delta-io/connectors pull request #354
Opened 2022-05-31 21:35 UTC by 6a0juu

Currently VersionLog.getActions returns a list of actions. We would like Iterator to avoid memory pressure.

2022-05-31 21:53 UTC, scottsand-db requested changes
looks great! looking forward to seeing some tests. thanks for doing this!

2022-05-31 21:53 UTC, scottsand-db commented on standalone/src/main/java/io/delta/standalone/VersionLog.java
> +        actionIterator = actions.iterator();
why not move this `actionIterator` variable into the `new CloseableIterator<Action>() {` instance below?

2022-05-31 21:53 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/DeltaLogImpl.scala
> +      failOnDataLoss: Boolean): java.util.Iterator[MemoryOptimizedVersionLog] = {
nit: you can keep this as VersionLog.

2022-05-31 21:53 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/MemoryOptimizedVersionLog.scala
> +package io.delta.standalone.internal
nit: copyright

2022-05-31 21:53 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/MemoryOptimizedVersionLog.scala
> +private[internal] class MemoryOptimizedVersionLog(
nit: classdoc. what does this class do? what makes it special?

2022-05-31 21:53 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/MemoryOptimizedVersionLog.scala
> +          io.delta.standalone.internal.actions.Action.fromJson(stringIterator.next))
below you use `Action.fromJson` but here you are using `io.delta.standalone.internal.actions.Action.fromJson`. why the difference?

2022-05-31 21:53 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/MemoryOptimizedVersionLog.scala
> +    getNewActionIterator(supplier())
nit: you can just move the contents of `getNewActionIterator` here. no need to define an extra private method for it. why make me look here `getActionsIterator` only to have to then go and read another function `getNewActionIterator`?

2022-06-01 23:01 UTC, scottsand-db requested changes
Thanks for adding tests! Looking good. Left some comments.

2022-06-02 00:17 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/MemoryOptimizedVersionLog.scala
> +  extends io.delta.standalone.VersionLog(version, new java.util.ArrayList[ActionJ]()) {
you can just use `VersionLog` not `io.delta.standalone.VersionLog`

2022-06-02 00:21 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/DeltaLogImpl.scala
> +        () => store.read(p, hadoopConf)).asInstanceOf[VersionLog]
you don't need to do `.asInstanceOf[VersionLog]`.
`MemoryOptimizedVersionLog` _is a VersionLog_. It is a child of the parent.

2022-06-02 00:23 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/DeltaLogImpl.scala
> +        () => store.read(p, hadoopConf)).asInstanceOf[VersionLog]
but I told you earlier to keep the same interface. hm. let me think.

2022-06-02 05:20 UTC, 6a0juu commented on standalone/src/main/java/io/delta/standalone/VersionLog.java
> +        actionIterator = actions.iterator();
`actionIterator` is moved into [the instance](https://github.com/delta-io/connectors/pull/354/files#diff-d6ec31e5e8e28e2b824601cc142ee00166ba3a37bec5b2520eacbb1e850daef7R69)

2022-06-02 05:23 UTC, 6a0juu commented on standalone/src/main/scala/io/delta/standalone/internal/DeltaLogImpl.scala
> +      failOnDataLoss: Boolean): java.util.Iterator[MemoryOptimizedVersionLog] = {
This change reverted and added a type transformation at [here](https://github.com/delta-io/connectors/pull/354/files#diff-0ebc696377a1d97f1e3b082548ba108df4107da1429f0436ae2a84c4aba7c0f7R128)

2022-06-02 05:23 UTC, 6a0juu commented on standalone/src/main/scala/io/delta/standalone/internal/MemoryOptimizedVersionLog.scala
> +package io.delta.standalone.internal
Added [here](https://github.com/delta-io/connectors/pull/354/files#diff-c96de1028503f1efa5245b83b0c25240d4eb866edc7778a9ee70e929a4ff06a2R1)

2022-06-02 05:24 UTC, 6a0juu commented on standalone/src/main/scala/io/delta/standalone/internal/MemoryOptimizedVersionLog.scala
> +private[internal] class MemoryOptimizedVersionLog(
Class doc and method doc added, start from [here](https://github.com/delta-io/connectors/pull/354/files#diff-c96de1028503f1efa5245b83b0c25240d4eb866edc7778a9ee70e929a4ff06a2R28)

2022-06-02 05:26 UTC, 6a0juu commented on standalone/src/main/scala/io/delta/standalone/internal/MemoryOptimizedVersionLog.scala
> +          io.delta.standalone.internal.actions.Action.fromJson(stringIterator.next))
No difference, I wrote the full name because of some legacy dependency naming problems. Fixed [here](https://github.com/delta-io/connectors/pull/354/files#diff-c96de1028503f1efa5245b83b0c25240d4eb866edc7778a9ee70e929a4ff06a2R48)

2022-06-02 05:29 UTC, 6a0juu commented on standalone/src/main/scala/io/delta/standalone/internal/MemoryOptimizedVersionLog.scala
> +    getNewActionIterator(supplier())
Made `getNewActionIterator` anonymous and move to [here](https://github.com/delta-io/connectors/pull/354/files#diff-c96de1028503f1efa5245b83b0c25240d4eb866edc7778a9ee70e929a4ff06a2R39)

2022-06-02 05:33 UTC, 6a0juu commented on standalone/src/main/java/io/delta/standalone/VersionLog.java
> -    @Nonnull
I wonder if a null list in a `MemoryOptimizedVersionLog` instance will violate this annotation?

2022-06-02 05:43 UTC, 6a0juu commented on standalone/src/main/java/io/delta/standalone/VersionLog.java
> +import com.fasterxml.jackson.databind.JsonNode;
Removed. This is an auto-filling typo

2022-06-02 15:43 UTC, scottsand-db commented on standalone/src/main/java/io/delta/standalone/VersionLog.java
> +             * A wrapper class transforming {@code CloseableIterator<String>}
where is the `CloseableIterator<String>`? `actionIterator` is an `Iterator<Action>`.
I think you can delete this comment.
Also, this inline class is pretty trivial. You don't need this comment anyways

2022-06-02 15:44 UTC, scottsand-db commented on standalone/src/main/java/io/delta/standalone/VersionLog.java
> +
delete blank line

2022-06-02 15:45 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/DeltaLogImpl.scala
> +        .asInstanceOf[VersionLog]
another option is that we change DeltaLog.java API for `getChanges` from `Iterator<VersionLog>` to `Iterator<? extends VersionLog>`.

cc @vkorukanti .

in this case, we wouldn't need to use `.asInstanceOf`

2022-06-02 15:45 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/MemoryOptimizedVersionLog.scala
> +package io.delta.standalone.internal
btw @6a0juu please resolve comments once you have fixed the code.

2022-06-02 15:48 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/MemoryOptimizedVersionLog.scala
> +     * A wrapper class transforming [[CloseableIterator]] of [[String]]
nit: this comment should use `//` not `/**`

2022-06-02 15:48 UTC, scottsand-db commented on standalone/src/test/scala/io/delta/standalone/internal/VersionLogSuite.scala
> +     * Calling counter increased only when a new [[CloseableIterator]] is instantiated. i.e.
nit: this comment should use // not /**

2022-06-02 15:49 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/MemoryOptimizedVersionLog.scala
> +private[internal] class MemoryOptimizedVersionLog(
also describe the parameters. what is `version`, what is `supplier`.

2022-06-02 15:51 UTC, scottsand-db commented on standalone/src/test/scala/io/delta/standalone/internal/VersionLogSuite.scala
> +  test("CloseableIterator should not be instantiated when supplier is not used ") {
nit: extra space at end of test name

2022-06-02 15:51 UTC, scottsand-db commented on standalone/src/test/scala/io/delta/standalone/internal/VersionLogSuite.scala
> +      supplierWithCounter
`supplierWithCounter` is only ever used here. so why is it a class-level variable? why increase the scope of it?

2022-06-02 15:55 UTC, scottsand-db commented on standalone/src/test/scala/io/delta/standalone/internal/VersionLogSuite.scala
> +    anotherStringIterator = stringList.iterator
this is still a bad code smell IMO. you are updating a variable here .. during a test helper ... which mean the state of this class-level variable is dependent on when tests are being run.

I would try and find a way to re-write these tests without these dependencies / coupling between different tests and class-level variables.

2022-06-02 16:11 UTC, zsxwing commented
A high level suggestion: instead of adding a new subclass of VersionLog, can we make VersionLog smart enough like this?
```java
public final class VersionLog {
    private final long version;

    private List<Action> actions;

    private Supplier<CloseableIterator<Action>> actionsSupplier;

    VersionLog(long version, @Nonnull Supplier<CloseableIterator<Action>> actionsSupplier) {
        this.version = version;
        this.actionsSupplier = actionsSupplier;
        this.actions = null;
    }

    public VersionLog(long version, @Nonnull List<Action> actions) {
        this.version = version;
        this.actionsSupplier = null;
        this.actions = actions;
    }

    /**
     * @return the table version at which these actions occurred
     */
    public long getVersion() {
        return version;
    }

    /**
     * @return an unmodifiable {@code List} of the actions for this table version
     */
    @Nonnull
    public List<Action> getActions() {
        synchronized(this) {
            if (actions == null) {
                List<Action> localActions = new ArrayList<>();
                try(CloseableIterator<Action> iter = getActionsIterator()) {
                    while (iter.hasNext()) {
                        localActions.add(iter.next());
                    }
                    actions = localActions;
                } catch (IOException e) {
                    throw new UncheckedIOException(e);
                }
            }
        }
        return Collections.unmodifiableList(actions);
    }

    @Nonnull
    public CloseableIterator<Action> getActionsIterator() {
        synchronized (this) {
            if (actionsSupplier != null) {
                return actionsSupplier.get();
            } else {
                // create a `CloseableIterator` from `actions`
                return null;
            }
        }
    }
}
```
Benefits of this approach:
- If an existing user calls `getActions` multiple times today, they will not see any obvious difference.
- Not need to add a subclass.

2022-06-02 16:35 UTC, 6a0juu commented on standalone/src/main/java/io/delta/standalone/VersionLog.java
> -    @Nonnull
Oh it is an empty list. Added it back.

2022-06-02 16:37 UTC, 6a0juu commented on standalone/src/main/java/io/delta/standalone/VersionLog.java
> +             * A wrapper class transforming {@code CloseableIterator<String>}
Deleted

2022-06-02 16:40 UTC, 6a0juu commented on standalone/src/main/scala/io/delta/standalone/internal/MemoryOptimizedVersionLog.scala
> +  extends io.delta.standalone.VersionLog(version, new java.util.ArrayList[ActionJ]()) {
Fixed

2022-06-02 16:42 UTC, 6a0juu commented on standalone/src/main/scala/io/delta/standalone/internal/MemoryOptimizedVersionLog.scala
> +     * A wrapper class transforming [[CloseableIterator]] of [[String]]
Fixed

2022-06-02 16:44 UTC, 6a0juu commented on standalone/src/test/scala/io/delta/standalone/internal/VersionLogSuite.scala
> +  private def checkVersionLog(newVersionLog: VersionLog): Unit = {
Fixed [here](https://github.com/delta-io/connectors/pull/354/files#diff-31c34f77bca032d4c2f1ac05d83ac401f06ef496723b34ffc31543c2b53b87eaR99)

2022-06-02 16:45 UTC, 6a0juu commented on standalone/src/test/scala/io/delta/standalone/internal/VersionLogSuite.scala
> +  test("CloseableIterator should not be instantiated when supplier is not used ") {
Fixed

2022-06-02 16:47 UTC, 6a0juu commented on standalone/src/test/scala/io/delta/standalone/internal/VersionLogSuite.scala
> +     * Calling counter increased only when a new [[CloseableIterator]] is instantiated. i.e.
Fixed

2022-06-02 16:49 UTC, 6a0juu commented on standalone/src/test/scala/io/delta/standalone/internal/VersionLogSuite.scala
> +      supplierWithCounter
Moved `applyCounter` and `supplierWithCounter` into the test

2022-06-02 16:50 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/MemoryOptimizedVersionLog.scala
> +    .toList
you could save this result to a private variable, and then return Collections.unmodifiableList(_private_list). this is more performant.

2022-06-02 17:08 UTC, 6a0juu commented on standalone/src/main/scala/io/delta/standalone/internal/MemoryOptimizedVersionLog.scala
> +  override def getActions: java.util.List[ActionJ] = {
Fixed

2022-06-02 17:09 UTC, 6a0juu commented on standalone/src/test/scala/io/delta/standalone/internal/VersionLogSuite.scala
> +      s"versionLog.getVersion() should be ${defaultVersionNumber} other than " +
Clue deleted

2022-06-02 17:10 UTC, 6a0juu commented on standalone/src/main/java/io/delta/standalone/VersionLog.java
> +            final Iterator<Action> actionIterator = actions.iterator();
Fixed

2022-06-02 17:12 UTC, 6a0juu commented on standalone/src/test/scala/io/delta/standalone/internal/VersionLogSuite.scala
> +        var applyCounter: Int = 0
Fixed

2022-06-02 17:51 UTC, 6a0juu commented on standalone/src/main/scala/io/delta/standalone/internal/MemoryOptimizedVersionLog.scala
> +private[internal] class MemoryOptimizedVersionLog(
[New doc] added

2022-06-02 20:36 UTC, 6a0juu commented
Closed this PR. Made new PR based on @zsxwing implementation [here](https://github.com/delta-io/connectors/pull/363)

2022-06-03 21:55 UTC, 6a0juu commented on standalone/src/main/scala/io/delta/standalone/internal/DeltaLogImpl.scala
> +        .asInstanceOf[VersionLog]
[Here](https://github.com/6a0juu/connectors/runs/6732843754?check_suite_focus=true#step:8:218) I met an error with generic type casting while using `Iterator<? extends VersionLog>`. Found [some reason](https://users.scala-lang.org/t/return-generic-type-and-upcast/4356/4) for this. Here are 3 solutions:
- Convert all `VersionLog` to `MemoryOptimizedVersionLog` in Flink test.
- Still use `.asInstanceOf`.
- Make an interface over 2 implementations.

2022-06-03 21:57 UTC, zsxwing commented on standalone/src/main/scala/io/delta/standalone/internal/MemoryOptimizedVersionLog.scala
> +  private var _private_action_list: Option[java.util.List[ActionJ]] = None
We can use Scala lazy to simplify the code
```suggestion
  private lazy val cachedActions: java.util.List[ActionJ] = {
    // put the converting code here.
  }
```

2022-06-03 21:58 UTC, 6a0juu commented on standalone/src/main/scala/io/delta/standalone/internal/MemoryOptimizedVersionLog.scala
> +    .toList
Made some exception re-throwing efforts [here](https://github.com/delta-io/connectors/pull/354/files#diff-c96de1028503f1efa5245b83b0c25240d4eb866edc7778a9ee70e929a4ff06a2R61)

2022-06-03 22:05 UTC, zsxwing commented on standalone/src/main/scala/io/delta/standalone/internal/DeltaLogImpl.scala
> +        .asInstanceOf[VersionLog]
We can change `deltaPaths.map { status =>` to `deltaPaths.map[VersionLog]` to tell Scala to pick up the parent class.

2022-06-03 22:08 UTC, 6a0juu commented on standalone/src/main/scala/io/delta/standalone/internal/MemoryOptimizedVersionLog.scala
> +  private var _private_action_list: Option[java.util.List[ActionJ]] = None
[Updated](https://github.com/delta-io/connectors/pull/354/files#diff-c96de1028503f1efa5245b83b0c25240d4eb866edc7778a9ee70e929a4ff06a2R51)

2022-06-03 22:08 UTC, zsxwing commented on standalone/src/main/scala/io/delta/standalone/internal/MemoryOptimizedVersionLog.scala
> +  private lazy val _private_action_list: java.util.List[ActionJ] = {
nit: We use `camel case`. This can be called `cachedActions`.

2022-06-03 22:46 UTC, 6a0juu commented on standalone/src/main/scala/io/delta/standalone/internal/MemoryOptimizedVersionLog.scala
> +  private lazy val _private_action_list: java.util.List[ActionJ] = {
[Updated](https://github.com/delta-io/connectors/pull/354/files#diff-c96de1028503f1efa5245b83b0c25240d4eb866edc7778a9ee70e929a4ff06a2R51)

2022-06-03 22:51 UTC, 6a0juu commented on standalone/src/test/scala/io/delta/standalone/internal/VersionLogSuite.scala
> +    anotherStringIterator = stringList.iterator
Change the variables to functions [here](https://github.com/delta-io/connectors/pull/354/commits/650396808340bf3dedb295dfd29f6b91fc4f364e#diff-31c34f77bca032d4c2f1ac05d83ac401f06ef496723b34ffc31543c2b53b87eaR41) so we can make a new object for every test. No need to reset iterators during the test now.

2022-06-03 22:52 UTC, 6a0juu commented on standalone/src/main/scala/io/delta/standalone/internal/DeltaLogImpl.scala
> +        .asInstanceOf[VersionLog]
> We can change `deltaPaths.map { status =>` to `deltaPaths.map[VersionLog]` to tell Scala to pick up the parent class.

[Updated](https://github.com/delta-io/connectors/pull/354/commits/46dda69d7fdc92b53d1a149b92834fb1daa6259a#diff-0ebc696377a1d97f1e3b082548ba108df4107da1429f0436ae2a84c4aba7c0f7R117)

2022-06-03 22:59 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/MemoryOptimizedVersionLog.scala
> +        Try(ConversionUtils.convertAction(Action.fromJson(stringIterator.next))).recover {
why was this needed?

2022-06-03 23:04 UTC, 6a0juu commented on standalone/src/main/scala/io/delta/standalone/internal/MemoryOptimizedVersionLog.scala
> +        Try(ConversionUtils.convertAction(Action.fromJson(stringIterator.next))).recover {
This change is based on [Ryan's comment](https://github.com/delta-io/connectors/pull/354#issuecomment-1145050152) ensuring thread-safe. I am not sure the call stack behind `.next()` method but it probably will raise error when multiple threads are consuming one `stringIterator`?

2022-06-04 03:22 UTC, zsxwing reviewed
Overall looks good. Left a few nits. Mostly style issues.

2022-06-04 03:22 UTC, zsxwing commented on standalone/src/main/scala/io/delta/standalone/internal/MemoryOptimizedVersionLog.scala
> +  override def getActions: java.util.List[ActionJ] = this.synchronized {
Remove `this.synchronized`. `lazy val` is thread safe.

2022-06-04 03:22 UTC, zsxwing commented on standalone/src/main/scala/io/delta/standalone/internal/MemoryOptimizedVersionLog.scala
> +    // io.delta.standalone.internal.util.Implicits.CloseableIteratorOps.toArray
nit: remove unused comments

2022-06-04 03:22 UTC, zsxwing commented on standalone/src/main/scala/io/delta/standalone/internal/MemoryOptimizedVersionLog.scala
> +  /** @return an unmodifiable [[List]] of [[Action]] for this table version */
nit: remove this. We don't need to copy the comment from the parent class

2022-06-04 03:22 UTC, zsxwing commented on standalone/src/main/scala/io/delta/standalone/internal/MemoryOptimizedVersionLog.scala
> +      @throws[java.io.IOException]
nit: this is not needed as we are in Scala

2022-06-04 03:22 UTC, zsxwing commented on standalone/src/main/scala/io/delta/standalone/internal/MemoryOptimizedVersionLog.scala
> +      private val stringIterator = supplier.apply()
nit: 
```suggestion
      private val stringIterator = supplier()
```

2022-06-04 03:22 UTC, zsxwing commented on standalone/src/main/scala/io/delta/standalone/internal/MemoryOptimizedVersionLog.scala
> +      @throws[java.io.IOException]
nit: remove this as it's not needed in Scala.

2022-06-04 03:22 UTC, zsxwing commented on standalone/src/main/scala/io/delta/standalone/internal/MemoryOptimizedVersionLog.scala
> +        Try(ConversionUtils.convertAction(Action.fromJson(stringIterator.next))).recover {
The returned Iterator is okay to not be thread-safe. My comment is mostly for `getActions` which we are going to cache `actions`. Scala `lazy val` would provide the guarantee and we don't need to do extra work.

This method can be as simple as you did before
```
ConversionUtils.convertAction(Action.fromJson(stringIterator.next()))
```

2022-06-04 03:22 UTC, zsxwing commented on standalone/src/main/scala/io/delta/standalone/internal/MemoryOptimizedVersionLog.scala
> +  override def getActionsIterator: CloseableIterator[ActionJ] = this.synchronized {
Remove `this.synchronized`.

2022-06-04 03:22 UTC, zsxwing commented on standalone/src/main/scala/io/delta/standalone/internal/MemoryOptimizedVersionLog.scala
> +  /** @return an [[CloseableIterator]] of [[Action]] for this table version */
nit: remove this. We don't need to copy the comment from the parent class

2022-06-04 06:25 UTC, 6a0juu commented on standalone/src/main/scala/io/delta/standalone/internal/MemoryOptimizedVersionLog.scala
> +      @throws[java.io.IOException]
Just curious, what would happen if the called methods throws a java exception to Scala?

2022-06-05 03:29 UTC, zsxwing approved these changes

2022-06-06 15:42 UTC, scottsand-db commented on standalone/src/test/scala/io/delta/standalone/internal/VersionLogSuite.scala
> +import scala.collection.JavaConverters._
wrong import order

2022-06-06 15:44 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/MemoryOptimizedVersionLog.scala
> +      .toList
you've lost the comment that says how this is automatically closed.

2022-06-06 15:45 UTC, scottsand-db commented on standalone/src/test/scala/io/delta/standalone/internal/VersionLogSuite.scala
> +      .count(x => x._1 == x._2) == newActionList.size())
what is this testing?

2022-06-06 15:45 UTC, scottsand-db commented on standalone/src/test/scala/io/delta/standalone/internal/VersionLogSuite.scala
> +
nit: delete empty link

2022-06-06 15:46 UTC, scottsand-db commented on standalone/src/test/scala/io/delta/standalone/internal/VersionLogSuite.scala
> +
nit: delete empty link

2022-06-06 16:20 UTC, scottsand-db commented on standalone/src/test/scala/io/delta/standalone/internal/VersionLogSuite.scala
> +      .count(x => x._1 == x._2) == newActionList.size())
isn't that what `assert(newActionIterator.next() == actionCloseableIterator.next())` is checking below?

furthermore, instead of having each AddFile being the same (i.e. same path) `AddFile(1.toString, Map.empty, 1, 1, dataChange = true).json)`, each AddFile could have a unique path.

so during the `(1 to listLength)` call, you can also compare the paths

2022-06-06 16:55 UTC, 6a0juu commented on standalone/src/main/scala/io/delta/standalone/internal/MemoryOptimizedVersionLog.scala
> +        Try(ConversionUtils.convertAction(Action.fromJson(stringIterator.next))).recover {
Deleted

2022-06-06 16:55 UTC, 6a0juu commented on standalone/src/main/scala/io/delta/standalone/internal/MemoryOptimizedVersionLog.scala
> + * To save memory, full action list is loaded only when calling [[getActions]].
Updated

2022-06-06 16:56 UTC, 6a0juu commented on standalone/src/test/scala/io/delta/standalone/internal/VersionLogSuite.scala
> +import scala.collection.JavaConverters._
Fixed

2022-06-06 17:56 UTC, scottsand-db commented on standalone/src/test/scala/io/delta/standalone/internal/VersionLogSuite.scala
> +  private val actionList: java.util.List[ActionJ] = stringList
sorry, how is this "resolved"? It is still a modifiable list.

2022-06-06 21:00 UTC, 6a0juu commented on standalone/src/test/scala/io/delta/standalone/internal/VersionLogSuite.scala
> +      .count(x => x._1 == x._2) == newActionList.size())
`AddFile` with different path added [here](https://github.com/delta-io/connectors/pull/354/files#diff-31c34f77bca032d4c2f1ac05d83ac401f06ef496723b34ffc31543c2b53b87eaR36). And the comparison between action iterators is now [decided by path](https://github.com/delta-io/connectors/pull/354/files#diff-31c34f77bca032d4c2f1ac05d83ac401f06ef496723b34ffc31543c2b53b87eaR101).

And code is reformatted by `scalafmt`.

2022-06-06 21:27 UTC, scottsand-db commented on standalone/src/test/scala/io/delta/standalone/internal/VersionLogSuite.scala
> +      .tabulate(listLength)(x =>
using `tabulate` is fine, but most often in this code base we do `(0 until X).map { x => ... }` just an FYI.

2022-06-06 21:38 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/MemoryOptimizedVersionLog.scala
> + * the full action list is only instantiated when calling [[getActions]]. The memory occupied by
duplicate information in the javadoc

above you say `full action list is loaded only when calling [[getActions]].`. Here you repeat that info again, `the full action list is only instantiated when calling [[getActions]]`

2022-06-06 22:06 UTC, 6a0juu commented on standalone/src/main/scala/io/delta/standalone/internal/MemoryOptimizedVersionLog.scala
> + * the full action list is only instantiated when calling [[getActions]]. The memory occupied by
Removed duplicated description.

2022-06-06 22:11 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/MemoryOptimizedVersionLog.scala
> + * the full action list is only instantiated when calling [[getActions]]. The memory occupied by
`The memory occupied by action list is saved here when action list is long.`

We won't do any sort of check on the length of the action list, do we? Is this sentence correct?

2022-06-06 22:12 UTC, scottsand-db commented on standalone/src/test/scala/io/delta/standalone/internal/VersionLogSuite.scala
> +    (0 until listLength).map{ x =>
nit: `.map { x =>`

2022-06-06 22:17 UTC, 6a0juu commented on standalone/src/test/scala/io/delta/standalone/internal/VersionLogSuite.scala
> +    (0 until listLength).map{ x =>
Fixed it in the [next commit](https://github.com/delta-io/connectors/pull/354/commits/297c7cf14bcdebe7f03586cf2e3ca54f3d11c26f)

2022-06-06 22:18 UTC, scottsand-db commented on standalone/src/test/scala/io/delta/standalone/internal/VersionLogSuite.scala
> +    (0 until listLength).map{ x =>
Are you use? there needs to be a space after `.map`
correct: `.map { x =>`
incorrect: `.map{x =>`

2022-06-06 22:19 UTC, 6a0juu commented on standalone/src/test/scala/io/delta/standalone/internal/VersionLogSuite.scala
> +    (0 until listLength).map{ x =>
Extra space added

2022-06-06 22:20 UTC, 6a0juu commented on standalone/src/main/scala/io/delta/standalone/internal/MemoryOptimizedVersionLog.scala
> + * the full action list is only instantiated when calling [[getActions]]. The memory occupied by
We don't check the length. Class doc changed to `The memory is saved when [[getActions]] not been called`

2022-06-06 22:28 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/MemoryOptimizedVersionLog.scala
> + * action list is saved when [[getActions]] not been called.
is this sentence correct, too?

`The memory occupied by action list is saved when [[getActions]] not been called.`

I think "saved" is a confusing word here. Are we "saving/caching?" something? Or are we _not_ caching something and thus "saving/consuming" less memory?

2022-06-06 23:15 UTC, 6a0juu commented on standalone/src/main/scala/io/delta/standalone/internal/MemoryOptimizedVersionLog.scala
> + * action list is saved when [[getActions]] not been called.
Rewritten the detailed class description

2022-06-06 23:29 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/MemoryOptimizedVersionLog.scala
> + * memory than [[VersionLog]] with disabled [[getActions]].
I don't know what `disabled [[getActions]]` means. how is a method disabled?
feel free to run your next comment by me via Slack

2022-06-06 23:59 UTC, scottsand-db approved these changes
LGTM

2022-06-07 03:13 UTC, merged