Column stats expression type p0
delta-io/connectors pull request #413
Opened 2022-07-27 00:29 UTC by 6a0juu

Support following expression type in [column stats based file pruning](https://docs.google.com/document/d/1D2ukbGInriKTOZJl3r3pCZoQRji40rSuFgnOyzhHz7k/edit).
* equalTo
* greaterThan
* greaterThanOrEqual
* lessThan
* lessThanOrEqual
* OR 
* AND

2022-07-27 21:39 UTC, scottsand-db requested changes
Looking good. mainly just comments on your documentation.

2022-07-27 21:39 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/util/DataSkippingUtils.scala
> +   * @param ccRule     The building clRule when left and right children are both columns.
Your definition of `ccRule` starts by saying it is `The building clRule`. I'm confused.

2022-07-27 21:39 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/util/DataSkippingUtils.scala
> +   * @param clRule     The building clRule when left child is a column and right child is a literal
`clRule` isn't a proper known. So saying that the param `clRule` is "The building clRule" isn't helpful.

2022-07-27 21:39 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/util/DataSkippingUtils.scala
> +      case _ => None
it is worth mentioning here, or in the method doc, why we only care about Columns and Literals. Why not any other expressions?

IMO it is because these two are terminal / leaf expressions.

2022-07-27 21:39 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/util/DataSkippingUtils.scala
> +   * Now applied rules:
if you copied this logic from delta lake, which I think you have, then you should give a URL link the that original code/comment and say this is where we have derived this logic from.

2022-07-27 21:39 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/util/DataSkippingUtils.scala
> +   * (col1 == l1) -> (MIN.col1 <= l1 AND MAX.col1 >= l1)
IMO you should copy these individual comments to be beside the actual `case` statements below which implement them. That way, next to each case statement, is a simple human-readable comment that explains what's going on.

2022-07-27 21:39 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/util/DataSkippingUtils.scala
>      dataConjunction match {
why not just check if `dataConjunction` is empty early on?

that way you can match on `dataConjunction.get` instead of on `dataConjunction`.
This would mean that we don't have to wrap every case statement in `Some(...)`

2022-07-27 21:39 UTC, scottsand-db commented on standalone/src/test/scala/io/delta/standalone/internal/DataSkippingSuite.scala
> +   * Filter: (col2 == 1 && col2 == 2) (1 <= i <= 20)
you don't need the `(1 <= i <= 20)` here. does this significantly impact my understanding of this test case?

2022-07-27 21:39 UTC, scottsand-db commented on standalone/src/test/scala/io/delta/standalone/internal/DataSkippingUtilsSuite.scala
> +    // partial `And`: `IsNotNull` is not supported, only return one child as output.
what is "partial `And`"?

2022-07-27 21:39 UTC, scottsand-db commented on standalone/src/test/scala/io/delta/standalone/internal/DataSkippingUtilsSuite.scala
> +    // partial `And`: `IsNotNull` is not supported, only return one child as output.
have we implemented any sort of `partial and` implementation?

2022-07-27 22:55 UTC, 6a0juu commented on standalone/src/test/scala/io/delta/standalone/internal/DataSkippingUtilsSuite.scala
> +    // partial `And`: `IsNotNull` is not supported, only return one child as output.
Yes. [here](https://github.com/delta-io/connectors/pull/413/files#diff-ac21cc1184f49d8ec1b628b5106c84db06443f287ae0dfa16cf8aac5302be5f9R331) the `And` will return the non-null child when the other child get None value (the None returning is because of the unsupported expression type). This happens when building the column stats filter. Not when evaluating the filter.

2022-07-28 18:39 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/util/DataSkippingUtils.scala
> +   * @param lcRule     The building rule when left child is a literal value and left child is a
`when left child` ... `and left child`. you say `left` twice

2022-07-28 18:41 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/util/DataSkippingUtils.scala
> +   * @param ccRule     The building rule when left and right children are both columns.
if left and right children are both columns, why is the type `(Column, Column, Column, Column)`? 
basically, this is a complex parameter, and it isn't clear what all of its values are from the parameter description.

consider using case classes, with good documentation, instead of tuples.

2022-07-28 18:42 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/util/DataSkippingUtils.scala
> +        constructDataFilters(dataSchema, Some(lcRule(e1, e2)))
why does (Literal, Column) call `constructDataFilters` and yet `(Column, Literal)` does not?

2022-07-28 18:42 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/util/DataSkippingUtils.scala
> +        constructDataFilters(dataSchema, Some(lcRule(e1, e2)))
you should add inline comments explaining what each `case` statement is doing, and why they are different

2022-07-28 18:43 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/util/DataSkippingUtils.scala
> +   * Because they are the only two leaf expression types.
With all of these complex params, it isn't clear what precisely is being built here. You should add an example.

2022-07-28 18:48 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/util/DataSkippingUtils.scala
> +        val lcRule = (e1: Literal, e2: Column) => new EqualTo(e2, e1)
`e1` and `e2` aren't the most readable variable names. why not use `lit` and `col` and make the code super readable?

2022-07-28 18:56 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/util/DataSkippingUtils.scala
> +        val clRule = (minCol: Column, _: Column, e2: Literal) =>
yeah, why not make `clRule` and `lcRule` actual types?
```scala
private type ColLitRule = ....
```

2022-07-28 18:56 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/util/DataSkippingUtils.scala
> +        val clRule = (minCol: Column, _: Column, e2: Literal) =>
then you can just do `val clRule: ColLitRule = ....` and everything is typed nicely.

2022-07-28 18:59 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/util/DataSkippingUtils.scala
> +          // f(expr1 AND expr2) -> f(expr1) AND f(expr2)
if you reference "partial and" in another test, and you had to link me to this implementation here, then you should add a comment here explaining how you are implementing "partial and"

2022-07-28 19:01 UTC, scottsand-db commented on standalone/src/test/scala/io/delta/standalone/internal/DataSkippingSuite.scala
> +   * Reason: Because `IsNull` is currently unsupported in building column stats predicate,
will we ever support `IsNull`? What is the reason for not supporting it now?

2022-07-28 22:00 UTC, 6a0juu commented on standalone/src/main/scala/io/delta/standalone/internal/util/DataSkippingUtils.scala
> +   * @param ccRule     The building rule when left and right children are both columns.
Added parameter description for anonymous function.

2022-07-28 22:00 UTC, 6a0juu commented on standalone/src/test/scala/io/delta/standalone/internal/DataSkippingSuite.scala
> +   * Reason: Because `IsNull` is currently unsupported in building column stats predicate,
Changed this case to `IN`, we don't support `IN` because `IN`-list is not ordered so we cannot get the MIN and MAX value from it and cannot build the column stats filter. Please see [this](https://docs.google.com/document/d/1D2ukbGInriKTOZJl3r3pCZoQRji40rSuFgnOyzhHz7k/edit#heading=h.7wihkzdo7ims).

2022-07-28 22:37 UTC, scottsand-db requested changes

2022-07-28 22:37 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/util/DataSkippingUtils.scala
> +  private type ColColRule = (Column, Column, Column, Column) => Expression
Recall my comment here: https://github.com/delta-io/connectors/pull/413#discussion_r932562721

Personally, I think that using a `case class` is better than having to document the left min, right min, left max, etc etc.

private case class `ColColWrapper(leftMin: Column, leftMax: Column, ...`

Now this doesn't need any comments, because the code is self describing and clear

2022-07-28 22:37 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/util/DataSkippingUtils.scala
> +        val colColRule = (e1Min: Column, e1Max: Column, e2Min: Column, e2Max: Column) =>
Do you notice a lot of code duplication with all of this long tuple declarations?
Using case classes will solve that

2022-07-28 22:37 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/util/DataSkippingUtils.scala
> +        val leftMinMaxCol = getMinMaxColumn(dataSchema, e1.name).getOrElse { return None }
```scala
val (leftMin, leftMax) = getMinMaxColumn(dataSchema, e1.name).getOrElse { return None }
```

would be much clearer.

2022-07-28 22:37 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/util/DataSkippingUtils.scala
> +        Some(colColRule(leftMinMaxCol._1, leftMinMaxCol._2, rightMinMaxCol._1, rightMinMaxCol._2))
that way instead of `._1` and `._2` you can just use `leftMin` etc

2022-07-28 22:37 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/util/DataSkippingUtils.scala
> +  private type ColColRule = (Column, Column, Column, Column) => Expression
btw if you use this case class, you probably don't need to define the type ColColRule.
Since `ColColWrapper => Expression` is easy enough.

2022-07-28 22:37 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/util/DataSkippingUtils.scala
> +        val colColRule = (e1Min: Column, e1Max: Column, e2Min: Column, e2Max: Column) =>
so this would be
```scala
val colColRule = (w: ColColWrapper) => ... ... `w.leftMin, w.rightMax`
```
etc etc

2022-07-28 22:37 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/util/DataSkippingUtils.scala
> +        val colColRule = (e1Min: Column, e1Max: Column, e2Min: Column, e2Max: Column) =>
and this has much less code duplication

2022-07-29 00:35 UTC, scottsand-db requested changes

2022-07-29 00:35 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/util/DataSkippingUtils.scala
> +   * MIN of right child, MAX of right child.
you don't need these 2 lines. the code is self-describing

2022-07-29 00:35 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/util/DataSkippingUtils.scala
> +   * the literal value at the right child.
ditto

2022-07-29 00:35 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/util/DataSkippingUtils.scala
> +   * the column at the right child.
ditto

2022-07-29 00:35 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/util/DataSkippingUtils.scala
> +   * @param colColRule The building rule when left and right children are both columns.
`colColRule` and `ColColRule` is a little weird. One is a case class, the other is a function from that case class to `Expression`. This is inconsistent.

In [this](https://github.com/delta-io/connectors/pull/413#discussion_r932729748) comment I suggested `ColColWrapper`.

2022-07-29 00:35 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/util/DataSkippingUtils.scala
> +        val colLitRule = (r: ColLitRule) => new LessThan(r.leftMin, r.right)
much cleaner, eh :)

2022-07-29 00:35 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/util/DataSkippingUtils.scala
> +  private case class ColLitRule(leftMin: Column, leftMax: Column, right: Literal)
why not use `lit` instead of `right`?

2022-07-29 19:52 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/util/DataSkippingUtils.scala
> +        constructDataFilters(dataSchema, Some(litColRule(LitColWrapper(e1, e2))))
you still haven't answered my question here: https://github.com/delta-io/connectors/pull/413#discussion_r932563235.

2022-07-29 19:54 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/util/DataSkippingUtils.scala
> +        val colLitRule = (r: ColLitWrapper) => new GreaterThanOrEqual(r.leftMax, r.lit)
It's not clear to me why the order of `(col, lit)` or `(lit, col)` means that one of them uses the `max` (e.g. here you use r.leftMax), but the other does not (e.g. below you just use (r.col, r.lit)

2022-07-29 19:55 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/util/DataSkippingUtils.scala
> +      case (e1: Column, e2: Literal) =>
nit: using `col` and `e2` as variable names will make this more readable than `e1` and `e2`. little things like this make the code easier to read and maintain for future developers.

2022-07-29 19:56 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/util/DataSkippingUtils.scala
> +      case (e1: Column, e2: Literal) =>
This is very similar to my comment here: https://github.com/delta-io/connectors/pull/413#discussion_r932567764

2022-07-29 20:19 UTC, 6a0juu commented on standalone/src/main/scala/io/delta/standalone/internal/util/DataSkippingUtils.scala
> +        constructDataFilters(dataSchema, Some(lcRule(e1, e2)))
In `LitColRule`, we cast `(Literal, Column)` to `(Column, Literal)` format, with some expression type change. Also I have added the comment [here](https://github.com/delta-io/connectors/pull/413/files#diff-ac21cc1184f49d8ec1b628b5106c84db06443f287ae0dfa16cf8aac5302be5f9R246)

2022-07-29 20:19 UTC, 6a0juu commented on standalone/src/main/scala/io/delta/standalone/internal/util/DataSkippingUtils.scala
> +        constructDataFilters(dataSchema, Some(litColRule(LitColWrapper(e1, e2))))
In `LitColRule`, we cast `(Literal, Column)` to `(Column, Literal)` format, with some expression type change. Also I have added the comment [here](https://github.com/delta-io/connectors/pull/413/files#diff-ac21cc1184f49d8ec1b628b5106c84db06443f287ae0dfa16cf8aac5302be5f9R246)

2022-07-29 20:27 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/util/DataSkippingUtils.scala
> +        constructDataFilters(dataSchema, Some(litColRule(LitColWrapper(e1, e2))))
you state `by swap the left and right child` - where is this swap occurring?

2022-07-29 20:30 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/util/DataSkippingUtils.scala
> +        constructDataFilters(dataSchema, Some(litColRule(LitColWrapper(e1, e2))))
In other words, can you explain this to me please:
In my opinion, if we have `case (c: Column, l: Literal) => doSomething(c, l)` then when we have `case (l: Literal, c: Column)` it should perform `doSomething(c, l)`. Right now, your two different cases, which only change by the order of params, seem to be doing very very different things, and it's not clear to me why.

2022-07-29 20:31 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/util/DataSkippingUtils.scala
> +        constructDataFilters(dataSchema, Some(litColRule(LitColWrapper(e1, e2))))
You also stated, `In LitColRule, we cast (Literal, Column) to (Column, Literal) format` ... but `litColRule` is defined as a `The building rule when left child is a literal value and right child is a`. It doesn't mention anything about swapping.

Let me know if my position isn't clear enough and you'd like me to clarify something. Also, feel free to msg me and we can book a time to call and discuss this design. Cheers.

2022-07-29 20:38 UTC, 6a0juu commented on standalone/src/main/scala/io/delta/standalone/internal/util/DataSkippingUtils.scala
> +        val colLitRule = (r: ColLitWrapper) => new GreaterThanOrEqual(r.leftMax, r.lit)
Please see [here](https://github.com/delta-io/connectors/pull/413/files#diff-ac21cc1184f49d8ec1b628b5106c84db06443f287ae0dfa16cf8aac5302be5f9R247)

2022-07-29 20:59 UTC, 6a0juu commented on standalone/src/main/scala/io/delta/standalone/internal/util/DataSkippingUtils.scala
> +        constructDataFilters(dataSchema, Some(litColRule(LitColWrapper(e1, e2))))
Swapped the parameter order of `litColRule`. And I have updated the comments to 
```
// The `litColRule` will transform a binary expression from `expr(lit, col)` to
// `new_expr(col, lit)`. Afterwards `constructDataFilters` will use `colLitRule` to build
// the result from `new_expr(col, lit)` with `colLitRule`.
```

2022-07-29 21:48 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/util/DataSkippingUtils.scala
> +        constructDataFilters(dataSchema, Some(litColRule(LitColWrapper(e1, e2))))
@6a0juu - I'd suggest responding/answering the questions/comments above, instead of just pushing more code :)

For example, the question I asked you to explain [here](https://github.com/delta-io/connectors/pull/413#discussion_r933597732) is still not clear to me.

2022-07-29 21:56 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/util/DataSkippingUtils.scala
> +  private case class LitColWrapper(col: Column, lit: Literal)
why this change? the order of the parameters before made more sense, given that the class is called `LitColWrapper`, and not `ColLitWrapper`. If there was a past comment of mine that caused this or confused you, please feel free to call it out and ask for clarification.

2022-07-29 22:00 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/util/DataSkippingUtils.scala
> +        constructDataFilters(dataSchema, Some(litColRule(LitColWrapper(e1, e2))))
For example, I don't see how swapping the parameter order of `litColRule` resolves the above discussion.

2022-08-01 23:45 UTC, 6a0juu commented on standalone/src/main/scala/io/delta/standalone/internal/util/DataSkippingUtils.scala
> +        constructDataFilters(dataSchema, Some(litColRule(LitColWrapper(e1, e2))))
Thanks for the advice @scottsand-db ! I have updated the [class doc](https://github.com/delta-io/connectors/pull/413/files#diff-ac21cc1184f49d8ec1b628b5106c84db06443f287ae0dfa16cf8aac5302be5f9R259) with the relation ship of `buildBinaryComparatorFilter` and `constructDataFilters`, how the different rules handling different expression types, and how `litColRule` rewritten the expression and call `constructDataFilters` again to build the column stats filter.

2022-08-01 23:48 UTC, 6a0juu commented on standalone/src/main/scala/io/delta/standalone/internal/util/DataSkippingUtils.scala
> +        constructDataFilters(dataSchema, Some(litColRule(LitColWrapper(e1, e2))))
For your question about how `litColRule` works, my answer is:
When left child is literal value and right child is column, we use `litColRule`. This will rewrite the expression to `colLitRule` format (the left child is column and right child is literal value) in `buildBinaryComparatorFilter` and then use the rewritten expression to call `constructDataFilters` again to build the target expression by `colLitRule`.

2023-07-11 17:12 UTC, closed without merging

2023-07-11 17:25 UTC, vkorukanti commented
This repo has been deprecated and the code is moved under `connectors` module in https://github.com/delta-io/delta repository. [Here](https://github.com/delta-io/connectors/issues/556#issuecomment-1631207507) are the migration steps to recreate this PR in the new repository location.