Cache the partition pruning result in FilteredDeltaScanImpl to improve performance
delta-io/connectors pull request #419
Opened 2022-07-30 06:43 UTC by sonhmai

Cache the partition pruning result in FilteredDeltaScanImpl to improve performance (#399)
Signed-off-by: sonhmai <14060682+sonhmai@users.noreply.github.com>

2022-08-03 02:20 UTC, sonhmai commented on standalone/src/main/scala/io/delta/standalone/internal/scan/FilteredDeltaScanImpl.scala
> +  private val evaluationResults = mutable.Map.empty[Map[String, String], Boolean]
not using concurrent map here to leave control to client if the `Scan` needs to be accessed concurrently. I think the default case which happens most often is that `FilteredDeltaScanImpl` is used by only a single thread?

2022-08-03 02:21 UTC, sonhmai commented on standalone/src/main/scala/io/delta/standalone/internal/scan/FilteredDeltaScanImpl.scala
> +  private val evaluationResults = mutable.Map.empty[Map[String, String], Boolean]
safely(?) assumed here that the unique partition values Map can fit in memory.

2022-08-03 03:19 UTC, scottsand-db requested changes
Looking good! Just asked for
a) feature flag
b) micro benchmark with the flag turned on/off

2022-08-03 03:19 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/scan/FilteredDeltaScanImpl.scala
> +  private val evaluationResults = mutable.Map.empty[Map[String, String], Boolean]
> not using concurrent map here to leave control to client if the Scan needs to be accessed concurrently. I think the default case which happens most often is that FilteredDeltaScanImpl is used by only a single thread?

this SGTM.

2022-08-03 03:19 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/scan/FilteredDeltaScanImpl.scala
> +    val cachedResult = evaluationResults.get(addFile.partitionValues)
can you please wrap this behind a feature flag? you can add a hadoop conf constant to https://github.com/delta-io/connectors/blob/master/standalone/src/main/scala/io/delta/standalone/internal/sources/StandaloneHadoopConf.scala.

`partitionFilterRecordCaching.enabled`. Default to true.

When set to false, we will not use this partition filter record caching, presumably when the user is concerned about memory consumption. 

Please include good scaladoc describing the behaviour and usage of this hadoop conf.

As well, could you please add a microbenchmark? You can add a test set to `ignore` (which won't run the test) ... which creates, say, 100 commits, each with 10000 AddFiles, with, say, 100 unique partitions.

Then compare the runtime of this feature with the feature turned on and off.

2022-08-04 01:07 UTC, sonhmai commented on standalone/src/main/scala/io/delta/standalone/internal/scan/FilteredDeltaScanImpl.scala
> +    val cachedResult = evaluationResults.get(addFile.partitionValues)
sure, will do

2022-08-10 15:14 UTC, scottsand-db commented
@sonhmai - looking good! Could you add a micro benchmark? with perhaps a few layers of partitioning?

2022-08-10 15:14 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/scan/FilteredDeltaScanImpl.scala
> +  private lazy val evaluationResults = mutable.Map.empty[Map[String, String], Boolean]
nit we can remove `lazy`

2022-08-11 08:58 UTC, sonhmai commented on standalone/src/main/scala/io/delta/standalone/internal/scan/FilteredDeltaScanImpl.scala
> +  private lazy val evaluationResults = mutable.Map.empty[Map[String, String], Boolean]
thought about if the client disable the caching then the Map does not have to be initialized at all. It does not matter much though. We surely can remove `lazy` to keep things simple :D

2022-08-11 09:00 UTC, sonhmai commented
> @sonhmai - looking good! Could you add a micro benchmark? with perhaps a few layers of partitioning?

sure will do this. just pushed the other first

2022-08-17 10:00 UTC, sonhmai commented on standalone/src/main/scala/io/delta/standalone/internal/scan/FilteredDeltaScanImpl.scala
> +  private lazy val evaluationResults = mutable.Map.empty[Map[String, String], Boolean]
removed

2022-08-17 10:41 UTC, sonhmai commented on standalone/src/main/scala/io/delta/standalone/internal/scan/FilteredDeltaScanImpl.scala
> +    val cachedResult = evaluationResults.get(addFile.partitionValues)
maybe later we can have a separate issue to centralize the benchmarks with say JMH in a separate module? wdyt?

2022-08-17 10:49 UTC, sonhmai commented on standalone/src/main/scala/io/delta/standalone/internal/scan/FilteredDeltaScanImpl.scala
> +    val cachedResult = evaluationResults.get(addFile.partitionValues)
@scottsand-db pls review. thanks

2022-08-17 10:58 UTC, sonhmai commented on standalone/src/main/scala/io/delta/standalone/internal/scan/FilteredDeltaScanImpl.scala
> +    lazy val partitionRowRecord = new PartitionRowRecord(partitionSchema, addFile.partitionValues)
found thru benchmarking that creating this object can defy the purpose of caching, hence `lazy`

2022-08-18 18:45 UTC, scottsand-db approved these changes
LGTM! @sonhmai before I merge, can you please add the results of the micro benchmark to the PR description?

2022-08-19 02:34 UTC, sonhmai commented
> LGTM! @sonhmai before I merge, can you please add the results of the micro benchmark to the PR description?

@scottsand-db Added to the first comment. If that is not the right place, pls let me know.

2022-08-22 20:20 UTC, merged