Column stats file pruning: feature flag
delta-io/connectors pull request #421
Opened 2022-08-02 22:14 UTC by 6a0juu

Add a feature flag `DeltaConfigs.ENABLE_STATS_SKIPPING` to Delta Standalone.
This flag is in Boolean format and its default value is `false`.
When the flag is `true`, column stats based file pruning is enabled in `FilteredDeltaScan`.
When the flag is `false`, column stats based file pruning is disabled in `FilteredDeltaScan`.

2022-08-04 21:13 UTC, scottsand-db requested changes
Looking good, just need that one change from DeltaConfig -> hadoopConf configuration.

2022-08-04 21:13 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/DeltaConfig.scala
> +  val ENABLE_STATS_SKIPPING = buildConfig[Boolean](
as we discussed, this should instead of an at-runtime configuration set using the `hadoopConf` when you instantiate your DeltaLog, and you should add the key, along with good comments, to `StandaloneHadoopConf`

2022-08-04 21:13 UTC, scottsand-db commented on standalone/src/test/scala/io/delta/standalone/internal/DataSkippingSuite.scala
> +          col2Max(i) >= 1
you should add a comment here explaining what this is accomplishing

2022-08-04 21:13 UTC, scottsand-db commented on standalone/src/test/scala/io/delta/standalone/internal/DataSkippingSuite.scala
> +    // Stats skipping is enabled by default in this suite.
just in this suite? or in general?

2022-08-04 21:15 UTC, 6a0juu commented on standalone/src/test/scala/io/delta/standalone/internal/DataSkippingSuite.scala
> +    // Stats skipping is enabled by default in this suite.
I think in general it should be disabled by default. So we need to enable it manually here.

2022-08-04 22:18 UTC, 6a0juu commented on standalone/src/main/scala/io/delta/standalone/internal/DeltaConfig.scala
> +  val ENABLE_STATS_SKIPPING = buildConfig[Boolean](
Changed to the `StandaloneHadoopConf `

2022-08-04 22:27 UTC, scottsand-db requested changes

2022-08-04 22:27 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/SnapshotImpl.scala
> +  private val statsSkippingFlag = hadoopConf
nit: `statsSkippingEnabled`

2022-08-04 22:27 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/sources/StandaloneHadoopConf.scala
> +  val STATS_SKIPPING_KEY = "io.delta.standalone.STATS_SKIPPING_KEY"
`io.delta.standalone.statsSkipping.enabled`

2022-08-04 22:27 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/sources/StandaloneHadoopConf.scala
> +   * Key for the feature flag of column stats based file pruning in `FilteredDeltaScan`, `true` to
If enabled, per-column statistics will be used to perform file pruning (aka data skipping) in `DeltaScan::getFiles`. By default, this feature is enabled. Set to `false` to disable.

Also, make sure this is enabled by default.

2022-08-04 22:27 UTC, scottsand-db commented on standalone/src/test/scala/io/delta/standalone/internal/DataSkippingSuite.scala
> +      newConf.setBoolean(StandaloneHadoopConf.STATS_SKIPPING_KEY, true)
you shouldn't need to do this if the default value is true

2022-08-04 22:27 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/SnapshotImpl.scala
> +  private val statsSkippingFlag = hadoopConf
this isn't being used here. I would pass in `hadoopConf` to FilteredDeltaScanImpl instead.

2022-08-04 22:27 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/SnapshotImpl.scala
> +  private val statsSkippingFlag = hadoopConf
default `true`

2022-08-04 23:25 UTC, scottsand-db requested changes

2022-08-04 23:25 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/SnapshotImpl.scala
> +  private val statsSkippingEnabled = hadoopConf
delete this

2022-08-04 23:25 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/scan/FilteredDeltaScanImpl.scala
> +      // Evaluate the column stats filter when feature flag is true, partition filter passed, and
don't say "when feature flag is true". that's not specific enough. just say, "when stats skipping is enabled"

2022-08-04 23:25 UTC, scottsand-db commented on standalone/src/test/scala/io/delta/standalone/internal/DataSkippingSuite.scala
> +   * Second Output: All files.
this `first output` `second output` comments don't really mean much to a test. what is the "output" of a test?

why add it here? why not add it as inline comments inside the test?

2022-08-05 19:01 UTC, scottsand-db requested changes

2022-08-05 19:01 UTC, scottsand-db commented on standalone/src/test/scala/io/delta/standalone/internal/DataSkippingSuite.scala
> +    // Testing with stats skipping: The files will be filtered by `expectedResultWithStatsSkipping`.
i'm not sure if this comment makes sense. "The files will be filtered by `expectedResultWithStatsSkipping`."

The files will be filtered by a result? It's not clear to me how a "result" will filter files.

I think you can delete this comment.

2022-08-05 19:08 UTC, 6a0juu commented on standalone/src/test/scala/io/delta/standalone/internal/DataSkippingSuite.scala
> +    // Testing with stats skipping: The files will be filtered by `expectedResultWithStatsSkipping`.
Updated the comments with the actual stats filter.

2022-08-05 19:15 UTC, scottsand-db commented on standalone/src/test/scala/io/delta/standalone/internal/DataSkippingSuite.scala
> +    // `min.col1 <= 1 && max.col1 >= 1 && min.col2 <= 1 && max.col2 >= 1`.
this line doesn't need to be here. you've already defined this up above

2022-08-05 19:16 UTC, 6a0juu commented on standalone/src/test/scala/io/delta/standalone/internal/DataSkippingSuite.scala
> +    // `min.col1 <= 1 && max.col1 >= 1 && min.col2 <= 1 && max.col2 >= 1`.
Deleted it!

2022-08-05 20:37 UTC, scottsand-db approved these changes

2022-08-05 20:38 UTC, merged