Add DeltaConnectorConfiguration options to flink sink impl
delta-io/connectors pull request #425
Opened 2022-08-23 14:01 UTC by gopik

Extract option validator from source impl into a different package and reuse it from source and sink builders.
Closes #423

2022-08-23 14:04 UTC, kristoffSC commented on flink/src/main/java/io/delta/flink/options/BaseOptionTypeConverter.java
> +package io.delta.flink.options;
This has to stay under `internal`. 
Generally all classes that were under `internal` have to stay under that package.

the `internal` package is used to filter out classes for which we do not want to generate java docs via sbt-unidoc plugin.

2022-08-23 14:11 UTC, kristoffSC commented on flink/src/main/java/io/delta/flink/options/BaseOptionTypeConverter.java
> +package io.delta.flink.options;
This must stay under the internal package.

Generally all classes that were under internal have to stay under that package.

the internal package is used to filter out classes for which we do not want to generate java docs via sbt-unidoc plugin.

2022-08-23 14:13 UTC, kristoffSC commented
Quick, small note

Generally all classes that were under the `internal` have to stay under that package.
The `internal` package is used to filter out classes for which we do not want to generate java docs via sbt-unidoc plugin.

I see that you have moved a lot of classes out from that `internal` packed.  That have to stay like it was.

2022-08-23 15:14 UTC, gopik commented
I've move this to an internal package under io.delta.flink. Did you mean this or keeping them under respective source.internal and sink.internal (which implies a copy)?

2022-08-24 10:53 UTC, kristoffSC commented
> I've move this to an internal package under io.delta.flink. Did you mean this or keeping them under respective source.internal and sink.internal (which implies a copy)?

`io.delta.flink.internal` is great, thanks.

2022-08-24 17:29 UTC, gopik commented
@kristoffSC this is now ready for review.

2022-08-26 19:25 UTC, scottsand-db requested changes
This looks great! Thanks for doing this!

Left a few minor comments.

Could you also update the PR description showing how this new API can be used?

Also update the DeltaSinkBuilder javadoc showing an example.

Thanks!

2022-08-26 19:25 UTC, scottsand-db commented on flink/src/main/java/io/delta/flink/internal/options/OptionValidator.java
> +        Map<String, DeltaConfigOption<?>> validOptions) {
in general, we use this indentation:
```java
public OptionValidator(
        DeltaConnectorConfiguration config, // 8 space indent
        Map<String, DeltaConfigOption<?>> validOptions) {
    this.config = config; // 4 space indent
    this.validOptions = validOptions;
}
```

2022-08-26 19:25 UTC, scottsand-db commented on flink/src/main/java/io/delta/flink/internal/options/OptionValidator.java
> + * throws {@link IllegalArgumentException}.
let's make this even clearer to the user on how it is used: add a comment (class javadoc) saying that each Source and Sink will pass in their own `validOptions` map.

2022-08-26 19:25 UTC, scottsand-db commented on flink/src/main/java/io/delta/flink/sink/RowDataDeltaSinkBuilder.java
> +
nit: whitespace noise.

2022-08-26 19:25 UTC, scottsand-db commented on flink/src/main/java/io/delta/flink/sink/internal/DeltaSinkBuilder.java
> +
whitespace noise please delete

2022-08-29 13:44 UTC, kristoffSC commented on flink/src/main/java/io/delta/flink/internal/options/OptionValidator.java
> +    public void option(String optionName, String optionValue) {
nit: missing java doc comment that other overloaded methods have.

2022-08-29 13:51 UTC, kristoffSC commented on flink/src/main/java/io/delta/flink/internal/options/OptionValidator.java
> +    private void tryToSetOption(Executable argument) {
The same method and validation can be found in `DeltaSourceBuilderBase::tryToSetOption` method

I think it would nice to have a common code for such validation, specially that contract for .option is same for both Sink and Source

2022-08-29 13:57 UTC, kristoffSC commented on flink/src/main/java/io/delta/flink/internal/options/OptionValidator.java
> +public class OptionValidator {
Hi,
I think that `OptionValidator`  should not have `.option` methods in his API.
What if, someday we would want to add another version of .option method? We would have to propagate it on Builder and Validator.

I would think that `OptionValidation` only need `tryToSetOption` method.

Also I'm not sure about the name vs what it does. 
In Source builder we have the same kind of "validation" against valid option names, we have the same `tryToSetOption` method but all of that is a part of builder hence the "names" fits a little bit better. 

`OptionValidator` class name seems like a broad thing, validate name, values types?

2022-08-29 14:25 UTC, gopik commented on flink/src/main/java/io/delta/flink/internal/options/OptionValidator.java
> +public class OptionValidator {
@kristoffSC I agree that there's a duplication of option() functionality in builder and validator. The idea to extract this in it's own class was to isolate option processing in one place. Assuming we only keep tryToSetOption there, where should we have validateOptionName?

2022-09-05 10:03 UTC, kristoffSC commented on flink/src/main/java/io/delta/flink/internal/options/OptionValidator.java
> +public class OptionValidator {
The alternative would be to have a new abstract class that will be common base for both builders.
This new class could have `.option`, `validateOptionName` and `tryToSetOption` but I not feeling super comfortable to coupling Sink and Source classes with common class hierarchy. Composition is always favorable ;)

2022-09-06 18:06 UTC, gopik commented on flink/src/main/java/io/delta/flink/internal/options/OptionValidator.java
> +public class OptionValidator {
How about moving DeltaSourceValidationException -> DeltaOptionValidationException? There isn't anything source specific in that.

I've another question: I didn't understand why we need tryToSetOption and pass a runnable. It just seems to add another call that catches exception and wraps it. But the validation is already throwing runtime exceptions, so we don't need this right?

2022-09-06 19:06 UTC, gopik commented on flink/src/main/java/io/delta/flink/internal/options/OptionValidator.java
> +public class OptionValidator {
Ok, I now understand why we needed `tryToSetOption`. I've now created exception type for validation errors and it should cover the usage from source builder as well. Please take a look, if this looks ok, I'll update the source impl to use this as well.

2022-09-12 17:12 UTC, scottsand-db commented
@gopik this class hierarchy is getting a little complicated. could you please add a class diagram to the PR description showing the inheritance/composition relationship with the new API(s) you are proposing?

2022-09-12 17:25 UTC, scottsand-db requested changes

2022-09-12 17:25 UTC, scottsand-db commented on flink/src/main/java/io/delta/flink/internal/options/DeltaOptionValidationException.java
> +        return "Invalid Delta Source definition detected."
why does this exception say `Source`? mistake?

2022-09-12 17:25 UTC, scottsand-db commented on flink/src/main/java/io/delta/flink/internal/options/OptionValidator.java
> + *     // For any option set on the sink, pass it to validator. If it's successful, sinkConfig
"pass it to validator". should they use `.option` or `tryToSetOption`? You should give an example with each.

2022-09-12 17:25 UTC, scottsand-db commented on flink/src/test/java/io/delta/flink/internal/options/OptionValidatorTest.java
> +            validator.option("string", "'");
can you use a value better than `'`. why not `"value"`

2022-09-12 17:25 UTC, scottsand-db commented on flink/src/test/java/io/delta/flink/internal/options/OptionValidatorTest.java
> +            validator.option("", "'");
same here. this is just awkward to read. `"'"`

2022-09-12 17:25 UTC, scottsand-db commented on flink/src/main/java/io/delta/flink/sink/RowDataDeltaSinkBuilder.java
> +    public RowDataDeltaSinkBuilder option(String optionName, String optionValue) {
missing javadoc.

2022-09-12 17:25 UTC, scottsand-db commented on flink/src/main/java/io/delta/flink/sink/RowDataDeltaSinkBuilder.java
> +    private final DeltaConnectorConfiguration sinkConfiguration = new DeltaConnectorConfiguration();
this is not used in this PR, right? i.e. we are not setting any sink configurations.

can you please add a TODO comment here, saying to add and use sink configurations.

2022-09-13 12:15 UTC, gopik commented
> @gopik this class hierarchy is getting a little complicated. could you please add a class diagram to the PR description showing the inheritance/composition relationship with the new API(s) you are proposing?

There's no class hierarchy here. The proposal is to extract the option validation and exception out of source implementation into a common package and reuse it from source and sink builders.

2022-09-13 12:35 UTC, gopik commented on flink/src/main/java/io/delta/flink/internal/options/OptionValidator.java
> + *     // For any option set on the sink, pass it to validator. If it's successful, sinkConfig
tryToSetOption is private. Added .option in javadoc.

2022-09-13 12:36 UTC, gopik commented on flink/src/main/java/io/delta/flink/internal/options/OptionValidator.java
> +    private void tryToSetOption(Executable argument) {
Will update source implementation in a followup PR.

2022-09-13 12:36 UTC, gopik commented on flink/src/main/java/io/delta/flink/sink/internal/DeltaSinkOptions.java
> +
How about adding this in a followup PR?

2022-09-13 12:38 UTC, gopik commented on flink/src/main/java/io/delta/flink/sink/RowDataDeltaSinkBuilder.java
> +    private final DeltaConnectorConfiguration sinkConfiguration = new DeltaConnectorConfiguration();
There won't be an changes here when we add any sink configurations. This object stores computed options to be used by the sinkbuilder.

2022-09-13 12:38 UTC, gopik commented on flink/src/main/java/io/delta/flink/internal/options/DeltaOptionValidationException.java
> +        return "Invalid Delta Source definition detected."
Yes, it was a copy/paste error. fixed.

2022-09-13 12:41 UTC, gopik commented on flink/src/main/java/io/delta/flink/sink/internal/DeltaSinkOptions.java
> +
Let's add that in a followup PR?

2022-09-13 12:42 UTC, gopik commented on flink/src/main/java/io/delta/flink/internal/options/OptionValidator.java
> +    private void tryToSetOption(Executable argument) {
Will add source changes in followup PR.

2022-09-13 12:42 UTC, gopik commented on flink/src/test/java/io/delta/flink/internal/options/OptionValidatorTest.java
> +            validator.option("string", "'");
That was a mistake, intent was to have an empty string. Fixed.

2022-09-13 13:12 UTC, kristoffSC commented
@scottsand-db there were no changes to builder class hierarchy. 
For a moment there was a small discussion about creating new abstract class for builders, but I'm my opinion composition proposed and implemented by @gopik is a good choice.

2022-09-15 20:32 UTC, scottsand-db commented
@gopik - can you update the PR description? is this PR still incomplete?
also, the way you have added `OptionValidator` to `RowDataDeltaSinkBuilder` is very clean. Why haven't you also then added it to `DeltaSourceBuilderBase`? Seems like that would clean up the code alot.

`DeltaSourceBuilderBase` is even doing the same `tryToSetOption` calls...

2022-09-15 21:09 UTC, kristoffSC commented
> @gopik - can you update the PR description? is this PR still incomplete?
> also, the way you have added OptionValidator to RowDataDeltaSinkBuilder is very clean. Why haven't you also then added it to DeltaSourceBuilderBase? Seems like that would clean up the code alot.
> 
> DeltaSourceBuilderBase is even doing the same tryToSetOption calls...

@gopik  cc @scottsand-db 
Yeah I asked for the same thing in comment:
https://github.com/delta-io/connectors/pull/425#discussion_r957365388

I see you suggested to add it in a separate PR but I would strongly suggest to add it this one here and make it right at the beginning. It would not make this PR to grow significantly.
This PR is a good place since you are adding .option do Sink builder.

2022-09-16 15:39 UTC, scottsand-db commented on flink/src/main/java/io/delta/flink/internal/options/OptionValidator.java
> +        Exception e) {
nit: recall we want 8 space indentation here

2022-09-16 15:40 UTC, scottsand-db commented on flink/src/main/java/io/delta/flink/source/internal/builder/DeltaSourceBuilderBase.java
> +     * Validates sink configuration options.
`source` not `sink`

2022-09-17 16:55 UTC, gopik commented on flink/src/main/java/io/delta/flink/internal/options/OptionValidator.java
> +        Exception e) {
Isn't this 8 space indented, I'm seeing 8 spaces? Any intellij idea setting we can use to check this?

2022-09-17 16:56 UTC, gopik commented on flink/src/main/java/io/delta/flink/source/internal/builder/DeltaSourceBuilderBase.java
> +     * Validates sink configuration options.
Fixed.

2022-09-19 15:16 UTC, scottsand-db commented on flink/src/main/java/io/delta/flink/internal/options/OptionValidator.java
> +        Exception e) {
Your's is
```java
    private static DeltaOptionValidationException optionValidationException(
        Path tablePath,
        Exception e) {
        return new DeltaOptionValidationException(
            tablePath,
            Collections.singletonList(e.getClass() + " - " + e.getMessage())
        );
    }
```
but it should be
```java
    private static DeltaOptionValidationException optionValidationException(
            Path tablePath,
            Exception e) {
        return new DeltaOptionValidationException(
            tablePath,
            Collections.singletonList(e.getClass() + " - " + e.getMessage())
        );
    }
```

2022-09-19 15:16 UTC, scottsand-db commented on flink/src/main/java/io/delta/flink/internal/options/OptionValidator.java
> +        Exception e) {
are you still seeing 8 spaces? that would be `return new` was indented 8 spaces, too?

2022-09-21 02:24 UTC, gopik commented on flink/src/main/java/io/delta/flink/internal/options/OptionValidator.java
> +        Exception e) {
You are right, my bad I was looking at a wrong line, didn't check the line numbers. Will fix this, in case you are aware of intellij preference, please let me know.

2022-09-21 02:25 UTC, gopik commented on flink/src/main/java/io/delta/flink/internal/options/OptionValidator.java
> +        Exception e) {
You are right, my bad, i was looking at a different line. Will fix. Will check if there's any intellij pref that does this by default.

2022-10-13 16:11 UTC, scottsand-db approved these changes
LGTM.

2022-10-13 16:13 UTC, scottsand-db commented
@kristoffSC - can you take another look / LGTM this PR?

2022-10-24 20:18 UTC, kristoffSC approved these changes
LGTM :)

2022-10-24 20:21 UTC, kristoffSC commented on flink/src/test/java/io/delta/flink/sink/internal/DeltaSinkOptionsTest.java
> +import org.junit.Test;
please use Junit5 Test instead Junit4.

We are migrating all tests slowly to Junit5 so every new test should be using that one.

2022-10-24 20:23 UTC, kristoffSC commented
Added one small nit about using junit5 instead junit4 in new test class, other than that 
LGTM :) Thanks for your work @gopik

2022-10-24 20:55 UTC, scottsand-db commented
Ill merge once @gopik responds to the comments above.

2022-10-26 11:09 UTC, gopik commented
@scottsand-db Fixed the import to use junit5.

2022-10-28 18:32 UTC, kristoffSC approved these changes

2022-10-28 19:27 UTC, merged

2022-10-28 19:27 UTC, scottsand-db commented
Merged!