Internal API for higher protocol tables + CHECK constraints APIs
delta-io/connectors pull request #451
Opened 2022-10-20 03:39 UTC by allisonport-db

2022-10-20 04:31 UTC, allisonport-db commented
Still a few todo's in this code I'd like to resolve before merging (as well as some which are for later). But figured could start reviewing without those resolved

2022-10-20 04:32 UTC, allisonport-db commented on standalone/src/main/scala/io/delta/standalone/internal/exception/DeltaErrors.scala
> +  //  incompatibilities
I will do this before merge

2022-10-20 04:33 UTC, allisonport-db commented on standalone/src/test/scala/io/delta/standalone/internal/OptimisticTransactionSuite.scala
> +  // TODO: test appendOnly protocol check
I will also do this before merge

2022-10-20 20:56 UTC, scottsand-db commented
> We introduce the separate concepts of standalone's supported protocol version vs. the connector's supported protocol version. 

The connector's supported protocol version must be a subset of standalone's supported protocol version, right?

2022-10-20 21:32 UTC, scottsand-db requested changes

2022-10-20 21:32 UTC, scottsand-db commented on standalone/src/main/java/io/delta/standalone/Constraint.java
> + * - A column invariant which is stored in a column's metadata
add the code/class/reference for a "column's metadata"

2022-10-20 21:32 UTC, scottsand-db commented on standalone/src/main/java/io/delta/standalone/actions/Metadata.java
> +        // todo: get column invariants
would be great to keep track of all of these TODOs in the project plan / github issue tracking this project's progress

2022-10-20 21:32 UTC, scottsand-db commented on standalone/src/main/java/io/delta/standalone/actions/Metadata.java
> +        }
I don't think we need to throw an error here. All the user wants is to ensure that the constraint no longer exists. If it was never there to begin with, that should be fine.

Happy to be convinced otherwise.

2022-10-20 21:32 UTC, scottsand-db commented on standalone/src/main/java/io/delta/standalone/actions/Metadata.java
> +            throw DeltaErrors.checkConstraintAlreadyExists(name, configuration.get(fullKey));
does delta-on-spark throw an error?

2022-10-20 21:32 UTC, scottsand-db commented on standalone/src/main/java/io/delta/standalone/actions/Metadata.java
> +     * Add the specified check constraint to the {@code configuration}
IMO the `@return` statement seems more accurate+clear than this does.

There's can often be duplication between the method doc and the @return statement. I think it's fine to duplicate it verbatim, as that will make the javadoc most clear.

2022-10-20 21:32 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/DeltaLogImpl.scala
> +  private lazy val connectorWriterVersion = 2
you can put this comment in the code then

2022-10-20 21:32 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/DeltaLogImpl.scala
> +        throw new DeltaErrors.InvalidProtocolVersionException(
we should throw a different error. this error references `Delta Standalone`

2022-10-20 21:32 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/actions/actions.scala
> +  def checkMetadataProtocolCompatibility(metadata: Metadata, protocol: Protocol): Unit = {
`checkMetadataProtocolFeatureCompatibility` ?

2022-10-20 21:32 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/DeltaLogImpl.scala
> +        throw new DeltaErrors.InvalidProtocolVersionException(
nvm saw your comment below. can you include a `TODO` here too (about using a different error msg)? So Venki/the next reviewer doesn't repeat what I did

2022-10-20 21:32 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/DeltaLogImpl.scala
> +        throw new DeltaErrors.InvalidProtocolVersionException(
same as above. whoops. my bad. saw your explanation below.

2022-10-20 21:32 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/DeltaLogImpl.scala
> +    if (!ignoreConnectorProtocolChecks) {
i'm also not sure if having this flag be part of the deltaLog api is the best route / most scalable. will all our test-only flags be part of the delta log API?

I'm sure there's some scala/sbt way to check for a test flag instead without changing apis.

2022-10-20 21:39 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/DeltaLogImpl.scala
> +  private[standalone] def startTransactionWithInitialProtocolVersion(
can you update your PR description to say that `startTransactionWithInitialProtocolVersion` is just for testing?

2022-10-20 21:39 UTC, scottsand-db commented
@allisonport-db btw - didn't we decide this was going to target a feature branch?

2022-10-20 21:46 UTC, allisonport-db commented on standalone/src/main/java/io/delta/standalone/actions/Metadata.java
> +        }
I just followed what we do in sql when doing with a constraint that DNE
```
alter table table_name drop constraint constraint_name
```

2022-10-20 21:49 UTC, allisonport-db commented on standalone/src/main/java/io/delta/standalone/actions/Metadata.java
> +        String fullKey = Constraint.CHECK_CONSTRAINT_KEY_PREFIX + name.toLowerCase(Locale.ROOT);
This is a good point. On second thought I think we should perform some minor format verification that aligns with what we allow in spark (and I think we would block a name that already has the prefix)

2022-10-20 21:50 UTC, allisonport-db commented on standalone/src/main/java/io/delta/standalone/actions/Metadata.java
> +            throw DeltaErrors.checkConstraintAlreadyExists(name, configuration.get(fullKey));
yes

2022-10-20 22:07 UTC, allisonport-db commented on standalone/src/main/scala/io/delta/standalone/internal/DeltaLogImpl.scala
> +    if (!ignoreConnectorProtocolChecks) {
So currently this check is what maintains our current behavior when using the public APIs (i.e. a table with Protocol(1, 3) will pass the first check (Standalone's) but will fail this one still) while still being able to upgrade "Delta Standalone's" supported version.

My thinking was that in some tests, we want to only test Standalone's APIs directly without the concept of a "connector". This flag essentially allows us to do that. Likewise, for some tests we do want to test the behavior as a connector so we don't want `ignoreConnectorProtocolChecks=true` for all tests (for example, we have some current tests that make sure we cannot read/write to higher protocol tables through the public APIs.) Also eventually we will want to test these checks once we expand the public APIs.

2022-10-20 22:09 UTC, allisonport-db commented on standalone/src/main/scala/io/delta/standalone/internal/DeltaLogImpl.scala
> +    if (!ignoreConnectorProtocolChecks) {
Depending on how we choose to design it this might end up being very similar to the escape hatch we plan to provide connectors from the feature-protocol compatibility checks.

2022-10-20 22:11 UTC, allisonport-db commented on standalone/src/main/scala/io/delta/standalone/internal/DeltaLogImpl.scala
> +    if (!ignoreConnectorProtocolChecks) {
If you have a different idea I'm open to doing this in a different way (for example, we could set `connectorReaderVersion` and `connectorWriterVersion` to higher values to achieve a similar affect). This was just following the semantics of testing Standalone directly (no connector) vs. Standalone + connector

2022-10-20 22:14 UTC, allisonport-db commented on standalone/src/main/scala/io/delta/standalone/internal/DeltaLogImpl.scala
> +    if (!ignoreConnectorProtocolChecks) {
we can choose a different way to add/set this flag (although I do think it has to be a part of `DeltaLogImpl`)

2022-10-20 22:45 UTC, scottsand-db commented on standalone/src/main/java/io/delta/standalone/actions/Metadata.java
> +        }
IMO the decision to or not to throw an error is at a much higher scope than `Metadata.java`. So I think we should not throw an error here. IMO the connector can do that themselves.

Perhaps we can add a `hasCheckConstraint: Boolean` API so they can efficiently look it up?

WDYT @venki?

2022-10-20 22:48 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/actions/actions.scala
> +  val writerVersion = 5
can you remind me why this is safe to do? why can't we do it int by int ... feature by feature?

2022-10-21 00:12 UTC, allisonport-db commented on standalone/src/main/scala/io/delta/standalone/internal/actions/actions.scala
> +  val writerVersion = 5
Do you mean: as we add features, increase this? I considered this, but since we are implementing features non-linearly we would need a way to override this for testing purposes and that would be more complicated.

I think this is safe to do since we've set it up such that all public API behavior is unchanged (there are tests for this) and we don't plan to do a release or add the public APIs to read higher-protocol tables until all the features have been added.

2022-10-21 00:14 UTC, allisonport-db commented on standalone/src/main/scala/io/delta/standalone/internal/actions/actions.scala
> +  val writerVersion = 5
I think the alternative ways to allow testing a single feature non-linearly would be much more complicated.

2022-10-21 00:24 UTC, allisonport-db commented on standalone/src/main/scala/io/delta/standalone/internal/OptimisticTransactionImpl.scala
> -        s"Currently only Protocol readerVersion 1 and writerVersion 2 is supported.")
Should we fail if we see `writerVersion < 2` or will we now allow this?

2022-10-21 01:23 UTC, allisonport-db commented on standalone/src/main/scala/io/delta/standalone/internal/OptimisticTransactionImpl.scala
> +    assert(readerVersion <= Action.readerVersion && writerVersion <= Action.writerVersion,
#452

2023-07-11 17:12 UTC, closed without merging

2023-07-11 17:26 UTC, vkorukanti commented
This repo has been deprecated and the code is moved under `connectors` module in https://github.com/delta-io/delta repository. [Here](https://github.com/delta-io/connectors/issues/556#issuecomment-1631207507) are the migration steps to recreate this PR in the new repository location.