[WIP] Check constraint APIs
delta-io/connectors pull request #455
Opened 2022-10-25 19:52 UTC by allisonport-db

2022-10-25 22:31 UTC, allisonport-db commented on standalone/src/main/java/io/delta/standalone/actions/Metadata.java
> +    public Metadata addCheckConstraint(String name, String expression) throws Throwable {
`name` can be anything if it's escaped
```
\\ ie. this is a valid name:
name = '`delta.constraints`'
```

2022-10-25 22:40 UTC, scottsand-db commented
Can you update the target feature branch to be `support_higher_protocol_versions_feature_branch`

2022-10-26 21:37 UTC, scottsand-db requested changes

2022-10-26 21:37 UTC, scottsand-db commented on standalone/src/main/java/io/delta/standalone/Constraint.java
> +public final class Constraint {
do we ever expect or want OSS users to create their own constraint classes?

or do we just create a constraint instance .... and give them it... and they use it.

I'm wondering why a class instead of an interface.

2022-10-26 21:37 UTC, scottsand-db commented on standalone/src/test/scala/io/delta/standalone/internal/DeltaConstraintsSuite.scala
> +        // should not be retrieved
add a comment here (just one, not one per line) explaining why

2022-10-26 21:37 UTC, scottsand-db commented on standalone/src/main/java/io/delta/standalone/actions/Metadata.java
> +     * the specified check constraint added to the {@code configuration}
IMO it would be worth linking to the delta-core docs for check constraints.

Maybe even describe here in 1 line (TLDR) what a check constraint is.

(why? -> because even to me it's not super clear what the difference is)

2022-10-26 21:37 UTC, scottsand-db commented on standalone/src/main/java/io/delta/standalone/actions/Metadata.java
> +        Map<String, String> newConfiguration = new HashMap(configuration);
From about 5 mins of searching online ... it seems this doesn't do a deep clone. Let me know if I'm wrong.

https://www.baeldung.com/java-copy-hashmap

Also, please put in the method docs if this is intended to be a deep or shallow clone.

2022-10-26 22:24 UTC, allisonport-db commented on standalone/src/main/java/io/delta/standalone/actions/Metadata.java
> +        String prefixRegex = "^" + Constraint.CHECK_CONSTRAINT_KEY_PREFIX;
yeah good catch

2022-10-26 22:53 UTC, allisonport-db commented on standalone/src/main/java/io/delta/standalone/actions/Metadata.java
> +        Map<String, String> newConfiguration = new HashMap(configuration);
So it doesn't do a deep clone, but since configuration is Map<String, String> and Strings are immutable essentially shallow clone = deep clone (for the purpose of changing one does not modify the other). I also just ran some checks to verify this for sure

2022-10-26 22:56 UTC, allisonport-db commented on standalone/src/main/java/io/delta/standalone/actions/Metadata.java
> +        Map<String, String> newConfiguration = new HashMap(configuration);
honestly it was probably an initial oversight that `copyBuilder` doesn't do a deep copy of everything... this is something we should address what do you think?

2022-10-26 23:06 UTC, allisonport-db commented on standalone/src/main/java/io/delta/standalone/Constraint.java
> +    public static final String CHECK_CONSTRAINT_KEY_PREFIX = "delta.constraints.";
yeah sgtm this should be clarified here and in the @param docs for the get/remove methods

2022-10-26 23:15 UTC, allisonport-db commented on standalone/src/main/java/io/delta/standalone/actions/Metadata.java
> +     * the specified check constraint added to the {@code configuration}
oh I remember now...  check constraints are not documented currently in Protocol.md (is this what you were thinking of in terms of docs?). I'll add a short explanation and follow up on adding it to the protocol

2022-10-26 23:25 UTC, scottsand-db commented on standalone/src/main/java/io/delta/standalone/actions/Metadata.java
> +        Map<String, String> newConfiguration = new HashMap(configuration);
>  but since configuration is Map<String, String> and Strings are immutable essentially shallow clone = deep clone

SGTM.

for copybuilder, I wouldn't worry about it now.

2022-10-27 21:53 UTC, allisonport-db commented on standalone/src/main/java/io/delta/standalone/Constraint.java
> +    public static final String CHECK_CONSTRAINT_KEY_PREFIX = "delta.constraints.";
I'm thinking about moving this to the `Metadata` class what do you think?

2022-10-27 22:18 UTC, allisonport-db commented on standalone/src/main/java/io/delta/standalone/actions/Metadata.java
> +     * the specified check constraint added to the {@code configuration}
Added a short description. Once I update `Protocol.md` make sense to link it somewhere here

2022-10-31 18:27 UTC, allisonport-db commented on standalone/src/main/java/io/delta/standalone/actions/Metadata.java
> +            // todo: decide if we want to throw an error here
@vkorukanti @scottsand-db should we discuss this? I think @vkorukanti you commented on #456 that this is fine

2022-10-31 18:27 UTC, allisonport-db commented on standalone/src/main/java/io/delta/standalone/actions/Metadata.java
> +            // todo: decide if we want to throw an error here
@scottsand-db @vkorukanti same here

2022-10-31 23:59 UTC, scottsand-db commented on standalone/src/main/java/io/delta/standalone/actions/Metadata.java
> +            // todo: decide if we want to throw an error here
what do you think is the most common use case of this API? will they want to override by default? or do they NEVER want to accidentally override? I think answers to those questions will help us get our answer here.

2022-10-31 23:59 UTC, scottsand-db commented on standalone/src/main/java/io/delta/standalone/actions/Metadata.java
> +            // todo: decide if we want to throw an error here
if it doesn't contain it ... then no need to throw an error.

2022-11-01 00:00 UTC, scottsand-db commented on standalone/src/main/java/io/delta/standalone/actions/Metadata.java
> +            // todo: decide if we want to throw an error here
think of it from an API guarantee perspective: we guarantee that the metadata we return will not contain this check constraint.

the reason `withCheckConstraint` is different is because the user may or may not want to override the existing constraint.

but we don't need to worry about that here.

2022-11-01 00:01 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/ConstraintImpl.scala
> +    // todo: get column invariants
will this be done in another PR? can you add an "out of scope" section in your PR description listing all of the TODOs in this PR/future work that this pr has introduced?

or, if you think of a better place or way to present that information ^, then that is fine with me too.

2022-11-01 00:02 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/ConstraintImpl.scala
> +      : Seq[Constraint] = {
nit: please not this syntax it's ugly :D

2022-11-01 16:26 UTC, vkorukanti approved these changes
lgtm. Given that this PR is going to be in a feature branch, the pending TODOs can be addressed in separate PRs.

2022-11-01 18:16 UTC, allisonport-db commented on standalone/src/main/java/io/delta/standalone/actions/Metadata.java
> +            // todo: decide if we want to throw an error here
Do we expect our connectors to have the same behavior as the delta-spark SQL APIs for adding/removing check constraints? If we do, I think we should throw errors here (and below) and that error will just be propagated to the end user.

If we think connectors might not necessarily implement the same behavior as the SQL APIs, then this behavior is up for debate (and the `withoutCheckConstraint` should not throw an error) and we should expose an API `containsCheckConstraint` or something along those lines.

2022-11-01 18:35 UTC, allisonport-db commented on standalone/src/main/scala/io/delta/standalone/internal/ConstraintImpl.scala
> +    // todo: get column invariants
this is in #456 and is really just a placeholder

I can create a github issue with a checklist if that will help clarify everything (coming when I get the chance)

2022-11-01 21:04 UTC, scottsand-db commented on standalone/src/main/java/io/delta/standalone/actions/Metadata.java
> +            // todo: decide if we want to throw an error here
Sticking to the SQL API semantics (i.e. throw an error) SGTM

2022-11-01 21:04 UTC, scottsand-db approved these changes

2022-11-04 00:54 UTC, merged