Column Invariants
delta-io/connectors pull request #456
Opened 2022-10-26 01:08 UTC by allisonport-db

[wip]

2022-10-26 01:25 UTC, allisonport-db commented on standalone/src/test/scala/io/delta/standalone/internal/OptimisticTransactionSuite.scala
> +  // TODO: unblock these tests once we allow writerVersion=1
I commented out the blocking code for writerVersion=1 and ran this test

2022-10-26 03:11 UTC, allisonport-db commented on standalone/src/main/scala/io/delta/standalone/internal/util/InvariantUtils.scala
> +private[internal] object InvariantUtils {
95% copied from https://github.com/delta-io/delta/blob/master/core/src/main/scala/org/apache/spark/sql/delta/constraints/Invariants.scala

2022-10-26 03:12 UTC, allisonport-db commented on standalone/src/main/scala/io/delta/standalone/internal/util/SchemaUtils.scala
> +  def filterRecursively(
Completely copied from https://github.com/delta-io/delta/blob/master/core/src/main/scala/org/apache/spark/sql/delta/schema/SchemaUtils.scala#L55
except for minor API changes like `a.elementType` -> `a.getElementType` due to our Java getters

2022-10-26 21:44 UTC, scottsand-db requested changes
Minor comments.

2022-10-26 21:44 UTC, scottsand-db commented on standalone/src/main/java/io/delta/standalone/actions/Metadata.java
> +
nitty nit: noise

2022-10-26 21:44 UTC, scottsand-db commented on standalone/src/main/java/io/delta/standalone/actions/Metadata.java
> +        return Stream.concat(invariantConstraints.stream(), checkConstraints.stream())
do we want this return value to be modifiable? else we should probably do the `Collections.unmodifiableList(someList)`

2022-10-26 21:44 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/actions/actions.scala
> +      throw DeltaErrors.insufficientWriterVersion(protocol, 2, "columnInvariants")
`Protocol::checkMetadataFeatureProtocolCompatibility` --> is this for writers only? you are throwing `insufficientWriterVersion`?

maybe this is obvious and I am missing it but ... can we update the method doc to make this clearer?

2022-10-26 21:44 UTC, scottsand-db commented on standalone/src/test/scala/io/delta/standalone/internal/DeltaConstraintsSuite.scala
> +  def fieldMetadataWithInvariant(expr: String): FieldMetadata = {
private

2022-10-26 21:44 UTC, scottsand-db commented on standalone/src/test/scala/io/delta/standalone/internal/DeltaConstraintsSuite.scala
> +      expectedConstraints = Seq(new Constraint("EXPRESSION(col1 < 3)", "col1 < 3"))
so the _name_ of this is `EXPRESSION(col1 < 3)`? is that what Delta-Spark does? I'd expect `name` to be something more human readable.

2022-10-27 22:26 UTC, allisonport-db commented on standalone/src/test/scala/io/delta/standalone/internal/DeltaConstraintsSuite.scala
> +      expectedConstraints = Seq(new Constraint("EXPRESSION(col1 < 3)", "col1 < 3"))
Yes https://github.com/delta-io/delta/blob/master/core/src/main/scala/org/apache/spark/sql/delta/constraints/Invariants.scala#L57

2022-10-27 22:28 UTC, allisonport-db commented on standalone/src/main/scala/io/delta/standalone/internal/actions/actions.scala
> +      throw DeltaErrors.insufficientWriterVersion(protocol, 2, "columnInvariants")
So it depends on the feature. For writer-features it will throw `insufficientWriterVersion`. For reader _and_ writer features it can throw `insufficientProtocol`. For reader-features it will throw `insufficientReaderVersion`.

2022-10-27 22:28 UTC, allisonport-db commented on standalone/src/main/scala/io/delta/standalone/internal/actions/actions.scala
> +      throw DeltaErrors.insufficientWriterVersion(protocol, 2, "columnInvariants")
I can update the method docs

2022-10-28 15:18 UTC, vkorukanti commented on standalone/src/main/java/io/delta/standalone/actions/Metadata.java
> +    public Metadata addCheckConstraint(String name, String expression) throws Throwable {
nit: The method looks like we are to an existing Metadata. Usually`withCheckConstraint` seems to more appropriate given that it is returning a new Metadata object.

This method and the below one seem like a good candidates on the Builder object itself? Wdyt?
`metatadata.copyBuilder().addCheckConstraint().build()`
`metadata.copyBuilder().removeCheckConstraint().build()`

2022-10-28 15:29 UTC, vkorukanti commented on standalone/src/main/scala/io/delta/standalone/internal/actions/actions.scala
> +    if (InvariantUtils.getFromSchema(metadata.schema).size > 0 && protocol.minWriterVersion < 2) {
nit: add constants for required min reader and writer version.

2022-10-28 17:39 UTC, allisonport-db commented on standalone/src/main/java/io/delta/standalone/actions/Metadata.java
> +            // todo: decide if we want to throw an error here
Delta-spark throws an error.

2022-10-28 17:40 UTC, allisonport-db commented on standalone/src/main/java/io/delta/standalone/actions/Metadata.java
> +    public Metadata removeCheckConstraint(String name) throws Throwable {
Not case sensitive, I will add this to the method docs. Thanks :)

2022-10-28 21:46 UTC, allisonport-db commented on standalone/src/main/java/io/delta/standalone/actions/Metadata.java
> +    public Metadata addCheckConstraint(String name, String expression) throws Throwable {
I like moving the methods to the builder

2022-10-28 22:43 UTC, allisonport-db commented on standalone/src/main/java/io/delta/standalone/actions/Metadata.java
> +    public Metadata addCheckConstraint(String name, String expression) throws Throwable {
Updated in #455

2022-10-28 22:43 UTC, allisonport-db commented on standalone/src/main/scala/io/delta/standalone/internal/actions/actions.scala
> +    if (InvariantUtils.getFromSchema(metadata.schema).size > 0 && protocol.minWriterVersion < 2) {
#455

2022-11-07 18:27 UTC, allisonport-db commented on standalone/src/main/scala/io/delta/standalone/internal/util/SchemaUtils.scala
> +            && Option(newField.getMetadata.get(InvariantUtils.INVARIANTS_FIELD)).forall(
To avoid blocking _removing_ a column invariant. We don't provide any explicit APIs to do this, but it seems like something we might not want to explicitly block.

What do you think?

2022-11-07 18:28 UTC, allisonport-db commented on standalone/src/test/scala/io/delta/standalone/internal/DeltaConstraintsSuite.scala
> +        ConstraintImpl("EXPRESSION(nested is null)", "nested is null"))
Sure that's more realistic :)

2022-11-09 01:06 UTC, scottsand-db commented on standalone/src/test/scala/io/delta/standalone/internal/DeltaConstraintsSuite.scala
> +      fieldMetadataWithInvariant("col1 < 3"))
this wouldn't be part of `StructField` it would be a local private helper method in this test suite. e.g. see Venki's tests, he uses helpers like this to reduce verbosity

2022-11-09 01:08 UTC, scottsand-db commented on standalone/src/test/scala/io/delta/standalone/internal/DeltaConstraintsSuite.scala
> +      fieldMetadataWithInvariant("col1 < 3"))
but this isn't a big deal the code is still readable

2022-11-09 01:11 UTC, scottsand-db commented on standalone/src/test/scala/io/delta/standalone/internal/DeltaConstraintsSuite.scala
> +        fieldMetadataWithInvariant("col1 > 2"))
how will users be using this new public `Constraint` API?

e.g. here you have created a helper method to create an invariant. is that what we expect users to do?

2022-11-09 01:12 UTC, scottsand-db approved these changes
Looks good to me except for 1 remaining comment in SchemaUtils. I do want to keep track of these public API changes we are making, and perhaps starting to add examples so we keep track of the big picture (i.e. the public API, and how it will be used) to make sure we have a solid user journey using these new features.

2022-11-09 01:14 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/util/SchemaUtils.scala
> +            && Option(newField.getMetadata.get(InvariantUtils.INVARIANTS_FIELD)).forall(
Don't think I understand your answer.

I'm specifically referring to 

```scala
Option(newField.getMetadata.get(InvariantUtils.INVARIANTS_FIELD)).forall(_ == existingField.getMetadata.get(InvariantUtils.INVARIANTS_FIELD)))
```

To me this is like doing `Option(5).forall(_ == 7)`. Why not just do `5 == 7` ? Why do you need an `Option` ?

2022-11-09 01:28 UTC, allisonport-db commented on standalone/src/main/scala/io/delta/standalone/internal/util/SchemaUtils.scala
> +            && Option(newField.getMetadata.get(InvariantUtils.INVARIANTS_FIELD)).forall(
If `newField.getMetadata.get(InvariantUtils.INVARIANTS_FIELD)` is `null` (because the invariant has been removed) 

```
// this is true
Option(newField.getMetadata.get(InvariantUtils.INVARIANTS_FIELD))
    .forall(_ == existingField.getMetadata.get(InvariantUtils.INVARIANTS_FIELD)))

 // this is false
newField.getMetadata.get(InvariantUtils.INVARIANTS_FIELD) ==
    existingField.getMetadata.get(InvariantUtils.INVARIANTS_FIELD)
```

I'm open to just blocking removing an invariant though.

2022-11-09 01:30 UTC, allisonport-db commented on standalone/src/test/scala/io/delta/standalone/internal/DeltaConstraintsSuite.scala
> +        fieldMetadataWithInvariant("col1 > 2"))
we have added the public APIs for check constraints

2022-11-15 01:04 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/util/SchemaUtils.scala
> +            && Option(newField.getMetadata.get(InvariantUtils.INVARIANTS_FIELD)).forall(
what is the relationship between `def isStructWriteCompatible(_existingSchema: StructType, _newSchema: StructType): Boolean = {` and `I'm open to just blocking removing an invariant though.`?

i.e. is this an arbitrary decision? does it impact users?

2022-11-15 01:04 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/util/SchemaUtils.scala
> +            && Option(newField.getMetadata.get(InvariantUtils.INVARIANTS_FIELD)).forall(
is there a specific test case for this scenario?

2022-11-15 02:03 UTC, allisonport-db commented on standalone/src/main/scala/io/delta/standalone/internal/util/SchemaUtils.scala
> +            && Option(newField.getMetadata.get(InvariantUtils.INVARIANTS_FIELD)).forall(
Sorry the overall test name isn't accurate. Test is here https://github.com/delta-io/connectors/pull/456/files#diff-8af5d9c3c7304b98030b6ac30ff9b492293a542f5dadc3e44a7b3aa4ba5284c9R366

2022-11-15 02:26 UTC, allisonport-db commented on standalone/src/main/scala/io/delta/standalone/internal/util/SchemaUtils.scala
> +            && Option(newField.getMetadata.get(InvariantUtils.INVARIANTS_FIELD)).forall(
We can block any/all column-invariant schema changes for now, and can always unblock them in the future if needed.

We provide no public APIs for removing column invariants, but since they are technically deprecated, we might not want to explicitly block removing them from tables, but we can always change this later if it's necessary. Also removing them isn't really a protocol violation, where as adding or changing them could be since existing data would need to be checked.

2022-11-15 18:07 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/util/SchemaUtils.scala
> +            && Option(newField.getMetadata.get(InvariantUtils.INVARIANTS_FIELD)).forall(
is this what delta-spark does?

2022-11-15 18:42 UTC, scottsand-db commented on standalone/src/main/scala/io/delta/standalone/internal/util/SchemaUtils.scala
> +            && Option(newField.getMetadata.get(InvariantUtils.INVARIANTS_FIELD)).forall(
Feel free to schedule a sync with me so we can just hash this out quickly instead of delaying the review across days :p

2022-12-01 19:07 UTC, scottsand-db approved these changes

2022-12-01 19:32 UTC, merged