#540 allow absolute paths
delta-io/connectors pull request #543
Opened 2023-04-24 17:18 UTC by aamend

In spark delta, we let end user create shallow clone objects by ignoring absolute paths through spark configuration. This change introduces the same logic for standalone delta through hadoop configuration (injected when creating a DeltaLog object). 

```scala
val conf = new Configuration()
conf.set("io.delta.vacuum.relativize.ignoreError", "true")
val deltaLog = DeltaLog.forTable(conf, path)
```

2023-04-25 18:39 UTC, dennyglee commented
Thanks @aamend  - @scottsand-db and @allisonport-db - let me know how I can help with this - thanks!

2023-04-28 01:25 UTC, allisonport-db commented
Sorry for any delay I will try to get to this tomorrow @aamend

2023-05-01 23:52 UTC, allisonport-db requested changes
Can you add tests for these changes?

2023-05-01 23:52 UTC, allisonport-db commented on standalone/src/main/java/io/delta/standalone/OptimisticTransaction.java
> +    String RELATIVE_PATH_IGNORE = "io.delta.vacuum.relativize.ignoreError";
You can instead add this to `StandaloneHadoopConf`

2023-05-01 23:52 UTC, allisonport-db commented on standalone/src/main/scala/io/delta/standalone/internal/OptimisticTransactionImpl.scala
> +        .get(OptimisticTransaction.RELATIVE_PATH_IGNORE, "false")
You can use hadoopConf.getBoolean here

2023-05-05 23:03 UTC, allisonport-db requested changes
Left a few minor comments. Should be good to merge after this

2023-05-06 00:36 UTC, aamend commented
Added minor fixes following your comments @allisonport-db . Thanks!

2023-05-09 00:53 UTC, allisonport-db commented on standalone/src/test/scala/io/delta/standalone/internal/OptimisticTransactionSuite.scala
> +      assert(committedPath.isAbsolute && !committedPath.isAbsoluteAndSchemeAuthorityNull)
check committedPath == "s3://snip/snip.parquet"?

2023-05-09 00:53 UTC, allisonport-db commented on standalone/src/main/scala/io/delta/standalone/internal/sources/StandaloneHadoopConf.scala
> +   * By default, this feature is enabled. Set to `false` to disable.
Isn't the default false? Set `true` to enable it?

2023-05-10 21:39 UTC, allisonport-db commented
Sorry I just realized this might affect more than just committing to the transaction. In particular I'm worried about this `canonicalizePath` https://github.com/delta-io/connectors/blob/master/standalone/src/main/scala/io/delta/standalone/internal/SnapshotImpl.scala#L350 that's used in the log replay. Seems like `fs.makeQualified(..)` might throw an error.

Can you look into this?

2023-05-10 22:49 UTC, aamend commented
`fs.makeQualified(..)` is only called if path is absolute AND scheme authority is null. For external files on s3, wasbs, adls, we won't try to qualify path. Added a test in DeltaScanSuite.scala just in case

2023-05-10 22:50 UTC, aamend commented
> Sorry I just realized this might affect more than just committing to the transaction. In particular I'm worried about this `canonicalizePath` https://github.com/delta-io/connectors/blob/master/standalone/src/main/scala/io/delta/standalone/internal/SnapshotImpl.scala#L350 that's used in the log replay. Seems like `fs.makeQualified(..)` might throw an error.
> 
> Can you look into this?

fs.makeQualified(..) is only called if path is absolute AND scheme authority is null. For external files on s3, wasbs, adls, we won't try to qualify path. Added a test in DeltaScanSuite.scala just in case

2023-05-12 00:01 UTC, allisonport-db approved these changes
LGTM

2023-05-12 00:02 UTC, merged